// flow-typed signature: 39c1ec51b14cfabfd4f8be7b41368443
// flow-typed version: <<STUB>>/add-asset-html-webpack-plugin_v2.1.3/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'add-asset-html-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'add-asset-html-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'add-asset-html-webpack-plugin/lib/addAllAssetsToCompilation' {
  declare module.exports: any;
}

declare module 'add-asset-html-webpack-plugin/lib/handleUrl' {
  declare module.exports: any;
}

declare module 'add-asset-html-webpack-plugin/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'add-asset-html-webpack-plugin/lib/addAllAssetsToCompilation.js' {
  declare module.exports: $Exports<'add-asset-html-webpack-plugin/lib/addAllAssetsToCompilation'>;
}
declare module 'add-asset-html-webpack-plugin/lib/handleUrl.js' {
  declare module.exports: $Exports<'add-asset-html-webpack-plugin/lib/handleUrl'>;
}
declare module 'add-asset-html-webpack-plugin/lib/index.js' {
  declare module.exports: $Exports<'add-asset-html-webpack-plugin/lib/index'>;
}
