// flow-typed signature: fdbf2ffdd439c0404b9b0f4f62e521ec
// flow-typed version: <<STUB>>/cache-loader_v1.2.2/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cache-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cache-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cache-loader/dist/cjs' {
  declare module.exports: any;
}

declare module 'cache-loader/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cache-loader/dist/cjs.js' {
  declare module.exports: $Exports<'cache-loader/dist/cjs'>;
}
declare module 'cache-loader/dist/index.js' {
  declare module.exports: $Exports<'cache-loader/dist/index'>;
}
