// flow-typed signature: 3131ae954331d1b27c15fdf710cb09a8
// flow-typed version: <<STUB>>/cache-loader_v^1.0.3/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cache-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cache-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cache-loader/dist/cjs' {
  declare module.exports: any;
}

declare module 'cache-loader/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cache-loader/dist/cjs.js' {
  declare module.exports: $Exports<'cache-loader/dist/cjs'>;
}
declare module 'cache-loader/dist/index.js' {
  declare module.exports: $Exports<'cache-loader/dist/index'>;
}
