// flow-typed signature: 3a6df7b083da4e398d8a6b86e9334ce2
// flow-typed version: <<STUB>>/eslint-plugin-prettier_v^2.0.1/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-prettier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-prettier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-prettier/lib/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-prettier/lib/rules/prettier' {
  declare module.exports: any;
}

declare module 'eslint-plugin-prettier/tests/lib/rules/prettier' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-prettier/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-prettier/lib/index'>;
}
declare module 'eslint-plugin-prettier/lib/rules/prettier.js' {
  declare module.exports: $Exports<'eslint-plugin-prettier/lib/rules/prettier'>;
}
declare module 'eslint-plugin-prettier/tests/lib/rules/prettier.js' {
  declare module.exports: $Exports<'eslint-plugin-prettier/tests/lib/rules/prettier'>;
}
