// flow-typed signature: adf60978cfe09cc7e4902dcdbb1309ce
// flow-typed version: <<STUB>>/firebase-tools_v^3.9.2/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'firebase-tools'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'firebase-tools' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'firebase-tools/commands/auth-export' {
  declare module.exports: any;
}

declare module 'firebase-tools/commands/auth-import' {
  declare module.exports: any;
}

declare module 'firebase-tools/commands/database-get' {
  declare module.exports: any;
}

declare module 'firebase-tools/commands/database-profile' {
  declare module.exports: any;
}

declare module 'firebase-tools/commands/database-push' {
  declare module.exports: any;
}

declare module 'firebase-tools/commands/database-remove' {
  declare module.exports: any;
}

declare module 'firebase-tools/commands/database-set' {
  declare module.exports: any;
}

declare module 'firebase-tools/commands/database-update' {
  declare module.exports: any;
}

declare module 'firebase-tools/commands/deploy' {
  declare module.exports: any;
}

declare module 'firebase-tools/commands/functions-config-clone' {
  declare module.exports: any;
}

declare module 'firebase-tools/commands/functions-config-get' {
  declare module.exports: any;
}

declare module 'firebase-tools/commands/functions-config-legacy' {
  declare module.exports: any;
}

declare module 'firebase-tools/commands/functions-config-set' {
  declare module.exports: any;
}

declare module 'firebase-tools/commands/functions-config-unset' {
  declare module.exports: any;
}

declare module 'firebase-tools/commands/functions-log' {
  declare module.exports: any;
}

declare module 'firebase-tools/commands/help' {
  declare module.exports: any;
}

declare module 'firebase-tools/commands/hosting-disable' {
  declare module.exports: any;
}

declare module 'firebase-tools/commands/index' {
  declare module.exports: any;
}

declare module 'firebase-tools/commands/init' {
  declare module.exports: any;
}

declare module 'firebase-tools/commands/list' {
  declare module.exports: any;
}

declare module 'firebase-tools/commands/login-ci' {
  declare module.exports: any;
}

declare module 'firebase-tools/commands/login' {
  declare module.exports: any;
}

declare module 'firebase-tools/commands/logout' {
  declare module.exports: any;
}

declare module 'firebase-tools/commands/open' {
  declare module.exports: any;
}

declare module 'firebase-tools/commands/serve' {
  declare module.exports: any;
}

declare module 'firebase-tools/commands/setup-web' {
  declare module.exports: any;
}

declare module 'firebase-tools/commands/tools-migrate' {
  declare module.exports: any;
}

declare module 'firebase-tools/commands/use' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/accountExporter' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/accountImporter' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/acquireRefs' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/api' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/auth' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/checkDupHostingKeys' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/checkValidTargetFilters' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/command' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/config' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/configstore' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/deploy/database/index' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/deploy/database/prepare' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/deploy/functions/deploy' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/deploy/functions/index' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/deploy/functions/prepare' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/deploy/functions/release' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/deploy/hosting/deploy' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/deploy/hosting/index' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/deploy/hosting/prepare' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/deploy/index' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/deploy/storage/index' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/deploy/storage/prepare' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/detectProjectRoot' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/ensureApiEnabled' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/ensureDefaultCredentials' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/error' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/errorOut' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/extractTriggers' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/fetchMOTD' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/fetchSetup' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/fetchWebSetup' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/filterTargets' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/fsutils' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/functionsConfig' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/functionsConfigClone' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/gcp/apikeys' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/gcp/cloudfunctions' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/gcp/cloudlogging' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/gcp/index' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/gcp/runtimeconfig' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/gcp/storage' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/getInstanceId' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/getProjectId' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/handlePreviewToggles' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/hosting/functionsProxy' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/hosting/implicitInit' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/hosting/initMiddleware' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/identifierToProjectId' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/init/features/database' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/init/features/functions' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/init/features/hosting' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/init/features/index' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/init/features/project' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/init/features/storage' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/init/index' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/listFiles' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/loadCJSON' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/loadRCFile' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/logError' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/logger' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/parseBoltRules' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/parseTriggers' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/prepareFunctionsUpload' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/prepareUpload' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/previews' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/profiler' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/profileReport' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/prompt' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/requireAccess' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/requireAuth' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/requireConfig' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/resolveProjectPath' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/responseToError' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/scopes' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/serve/functions' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/serve/hosting' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/serve/index' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/track' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/triggerParser' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/utils' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/validateJsonRules' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/validator' {
  declare module.exports: any;
}

declare module 'firebase-tools/templates/hosting/init' {
  declare module.exports: any;
}

declare module 'firebase-tools/templates/init/functions/index' {
  declare module.exports: any;
}

declare module 'firebase-tools/templates/setup/web' {
  declare module.exports: any;
}

// Filename aliases
declare module 'firebase-tools/commands/auth-export.js' {
  declare module.exports: $Exports<'firebase-tools/commands/auth-export'>;
}
declare module 'firebase-tools/commands/auth-import.js' {
  declare module.exports: $Exports<'firebase-tools/commands/auth-import'>;
}
declare module 'firebase-tools/commands/database-get.js' {
  declare module.exports: $Exports<'firebase-tools/commands/database-get'>;
}
declare module 'firebase-tools/commands/database-profile.js' {
  declare module.exports: $Exports<'firebase-tools/commands/database-profile'>;
}
declare module 'firebase-tools/commands/database-push.js' {
  declare module.exports: $Exports<'firebase-tools/commands/database-push'>;
}
declare module 'firebase-tools/commands/database-remove.js' {
  declare module.exports: $Exports<'firebase-tools/commands/database-remove'>;
}
declare module 'firebase-tools/commands/database-set.js' {
  declare module.exports: $Exports<'firebase-tools/commands/database-set'>;
}
declare module 'firebase-tools/commands/database-update.js' {
  declare module.exports: $Exports<'firebase-tools/commands/database-update'>;
}
declare module 'firebase-tools/commands/deploy.js' {
  declare module.exports: $Exports<'firebase-tools/commands/deploy'>;
}
declare module 'firebase-tools/commands/functions-config-clone.js' {
  declare module.exports: $Exports<'firebase-tools/commands/functions-config-clone'>;
}
declare module 'firebase-tools/commands/functions-config-get.js' {
  declare module.exports: $Exports<'firebase-tools/commands/functions-config-get'>;
}
declare module 'firebase-tools/commands/functions-config-legacy.js' {
  declare module.exports: $Exports<'firebase-tools/commands/functions-config-legacy'>;
}
declare module 'firebase-tools/commands/functions-config-set.js' {
  declare module.exports: $Exports<'firebase-tools/commands/functions-config-set'>;
}
declare module 'firebase-tools/commands/functions-config-unset.js' {
  declare module.exports: $Exports<'firebase-tools/commands/functions-config-unset'>;
}
declare module 'firebase-tools/commands/functions-log.js' {
  declare module.exports: $Exports<'firebase-tools/commands/functions-log'>;
}
declare module 'firebase-tools/commands/help.js' {
  declare module.exports: $Exports<'firebase-tools/commands/help'>;
}
declare module 'firebase-tools/commands/hosting-disable.js' {
  declare module.exports: $Exports<'firebase-tools/commands/hosting-disable'>;
}
declare module 'firebase-tools/commands/index.js' {
  declare module.exports: $Exports<'firebase-tools/commands/index'>;
}
declare module 'firebase-tools/commands/init.js' {
  declare module.exports: $Exports<'firebase-tools/commands/init'>;
}
declare module 'firebase-tools/commands/list.js' {
  declare module.exports: $Exports<'firebase-tools/commands/list'>;
}
declare module 'firebase-tools/commands/login-ci.js' {
  declare module.exports: $Exports<'firebase-tools/commands/login-ci'>;
}
declare module 'firebase-tools/commands/login.js' {
  declare module.exports: $Exports<'firebase-tools/commands/login'>;
}
declare module 'firebase-tools/commands/logout.js' {
  declare module.exports: $Exports<'firebase-tools/commands/logout'>;
}
declare module 'firebase-tools/commands/open.js' {
  declare module.exports: $Exports<'firebase-tools/commands/open'>;
}
declare module 'firebase-tools/commands/serve.js' {
  declare module.exports: $Exports<'firebase-tools/commands/serve'>;
}
declare module 'firebase-tools/commands/setup-web.js' {
  declare module.exports: $Exports<'firebase-tools/commands/setup-web'>;
}
declare module 'firebase-tools/commands/tools-migrate.js' {
  declare module.exports: $Exports<'firebase-tools/commands/tools-migrate'>;
}
declare module 'firebase-tools/commands/use.js' {
  declare module.exports: $Exports<'firebase-tools/commands/use'>;
}
declare module 'firebase-tools/index' {
  declare module.exports: $Exports<'firebase-tools'>;
}
declare module 'firebase-tools/index.js' {
  declare module.exports: $Exports<'firebase-tools'>;
}
declare module 'firebase-tools/lib/accountExporter.js' {
  declare module.exports: $Exports<'firebase-tools/lib/accountExporter'>;
}
declare module 'firebase-tools/lib/accountImporter.js' {
  declare module.exports: $Exports<'firebase-tools/lib/accountImporter'>;
}
declare module 'firebase-tools/lib/acquireRefs.js' {
  declare module.exports: $Exports<'firebase-tools/lib/acquireRefs'>;
}
declare module 'firebase-tools/lib/api.js' {
  declare module.exports: $Exports<'firebase-tools/lib/api'>;
}
declare module 'firebase-tools/lib/auth.js' {
  declare module.exports: $Exports<'firebase-tools/lib/auth'>;
}
declare module 'firebase-tools/lib/checkDupHostingKeys.js' {
  declare module.exports: $Exports<'firebase-tools/lib/checkDupHostingKeys'>;
}
declare module 'firebase-tools/lib/checkValidTargetFilters.js' {
  declare module.exports: $Exports<'firebase-tools/lib/checkValidTargetFilters'>;
}
declare module 'firebase-tools/lib/command.js' {
  declare module.exports: $Exports<'firebase-tools/lib/command'>;
}
declare module 'firebase-tools/lib/config.js' {
  declare module.exports: $Exports<'firebase-tools/lib/config'>;
}
declare module 'firebase-tools/lib/configstore.js' {
  declare module.exports: $Exports<'firebase-tools/lib/configstore'>;
}
declare module 'firebase-tools/lib/deploy/database/index.js' {
  declare module.exports: $Exports<'firebase-tools/lib/deploy/database/index'>;
}
declare module 'firebase-tools/lib/deploy/database/prepare.js' {
  declare module.exports: $Exports<'firebase-tools/lib/deploy/database/prepare'>;
}
declare module 'firebase-tools/lib/deploy/functions/deploy.js' {
  declare module.exports: $Exports<'firebase-tools/lib/deploy/functions/deploy'>;
}
declare module 'firebase-tools/lib/deploy/functions/index.js' {
  declare module.exports: $Exports<'firebase-tools/lib/deploy/functions/index'>;
}
declare module 'firebase-tools/lib/deploy/functions/prepare.js' {
  declare module.exports: $Exports<'firebase-tools/lib/deploy/functions/prepare'>;
}
declare module 'firebase-tools/lib/deploy/functions/release.js' {
  declare module.exports: $Exports<'firebase-tools/lib/deploy/functions/release'>;
}
declare module 'firebase-tools/lib/deploy/hosting/deploy.js' {
  declare module.exports: $Exports<'firebase-tools/lib/deploy/hosting/deploy'>;
}
declare module 'firebase-tools/lib/deploy/hosting/index.js' {
  declare module.exports: $Exports<'firebase-tools/lib/deploy/hosting/index'>;
}
declare module 'firebase-tools/lib/deploy/hosting/prepare.js' {
  declare module.exports: $Exports<'firebase-tools/lib/deploy/hosting/prepare'>;
}
declare module 'firebase-tools/lib/deploy/index.js' {
  declare module.exports: $Exports<'firebase-tools/lib/deploy/index'>;
}
declare module 'firebase-tools/lib/deploy/storage/index.js' {
  declare module.exports: $Exports<'firebase-tools/lib/deploy/storage/index'>;
}
declare module 'firebase-tools/lib/deploy/storage/prepare.js' {
  declare module.exports: $Exports<'firebase-tools/lib/deploy/storage/prepare'>;
}
declare module 'firebase-tools/lib/detectProjectRoot.js' {
  declare module.exports: $Exports<'firebase-tools/lib/detectProjectRoot'>;
}
declare module 'firebase-tools/lib/ensureApiEnabled.js' {
  declare module.exports: $Exports<'firebase-tools/lib/ensureApiEnabled'>;
}
declare module 'firebase-tools/lib/ensureDefaultCredentials.js' {
  declare module.exports: $Exports<'firebase-tools/lib/ensureDefaultCredentials'>;
}
declare module 'firebase-tools/lib/error.js' {
  declare module.exports: $Exports<'firebase-tools/lib/error'>;
}
declare module 'firebase-tools/lib/errorOut.js' {
  declare module.exports: $Exports<'firebase-tools/lib/errorOut'>;
}
declare module 'firebase-tools/lib/extractTriggers.js' {
  declare module.exports: $Exports<'firebase-tools/lib/extractTriggers'>;
}
declare module 'firebase-tools/lib/fetchMOTD.js' {
  declare module.exports: $Exports<'firebase-tools/lib/fetchMOTD'>;
}
declare module 'firebase-tools/lib/fetchSetup.js' {
  declare module.exports: $Exports<'firebase-tools/lib/fetchSetup'>;
}
declare module 'firebase-tools/lib/fetchWebSetup.js' {
  declare module.exports: $Exports<'firebase-tools/lib/fetchWebSetup'>;
}
declare module 'firebase-tools/lib/filterTargets.js' {
  declare module.exports: $Exports<'firebase-tools/lib/filterTargets'>;
}
declare module 'firebase-tools/lib/fsutils.js' {
  declare module.exports: $Exports<'firebase-tools/lib/fsutils'>;
}
declare module 'firebase-tools/lib/functionsConfig.js' {
  declare module.exports: $Exports<'firebase-tools/lib/functionsConfig'>;
}
declare module 'firebase-tools/lib/functionsConfigClone.js' {
  declare module.exports: $Exports<'firebase-tools/lib/functionsConfigClone'>;
}
declare module 'firebase-tools/lib/gcp/apikeys.js' {
  declare module.exports: $Exports<'firebase-tools/lib/gcp/apikeys'>;
}
declare module 'firebase-tools/lib/gcp/cloudfunctions.js' {
  declare module.exports: $Exports<'firebase-tools/lib/gcp/cloudfunctions'>;
}
declare module 'firebase-tools/lib/gcp/cloudlogging.js' {
  declare module.exports: $Exports<'firebase-tools/lib/gcp/cloudlogging'>;
}
declare module 'firebase-tools/lib/gcp/index.js' {
  declare module.exports: $Exports<'firebase-tools/lib/gcp/index'>;
}
declare module 'firebase-tools/lib/gcp/runtimeconfig.js' {
  declare module.exports: $Exports<'firebase-tools/lib/gcp/runtimeconfig'>;
}
declare module 'firebase-tools/lib/gcp/storage.js' {
  declare module.exports: $Exports<'firebase-tools/lib/gcp/storage'>;
}
declare module 'firebase-tools/lib/getInstanceId.js' {
  declare module.exports: $Exports<'firebase-tools/lib/getInstanceId'>;
}
declare module 'firebase-tools/lib/getProjectId.js' {
  declare module.exports: $Exports<'firebase-tools/lib/getProjectId'>;
}
declare module 'firebase-tools/lib/handlePreviewToggles.js' {
  declare module.exports: $Exports<'firebase-tools/lib/handlePreviewToggles'>;
}
declare module 'firebase-tools/lib/hosting/functionsProxy.js' {
  declare module.exports: $Exports<'firebase-tools/lib/hosting/functionsProxy'>;
}
declare module 'firebase-tools/lib/hosting/implicitInit.js' {
  declare module.exports: $Exports<'firebase-tools/lib/hosting/implicitInit'>;
}
declare module 'firebase-tools/lib/hosting/initMiddleware.js' {
  declare module.exports: $Exports<'firebase-tools/lib/hosting/initMiddleware'>;
}
declare module 'firebase-tools/lib/identifierToProjectId.js' {
  declare module.exports: $Exports<'firebase-tools/lib/identifierToProjectId'>;
}
declare module 'firebase-tools/lib/init/features/database.js' {
  declare module.exports: $Exports<'firebase-tools/lib/init/features/database'>;
}
declare module 'firebase-tools/lib/init/features/functions.js' {
  declare module.exports: $Exports<'firebase-tools/lib/init/features/functions'>;
}
declare module 'firebase-tools/lib/init/features/hosting.js' {
  declare module.exports: $Exports<'firebase-tools/lib/init/features/hosting'>;
}
declare module 'firebase-tools/lib/init/features/index.js' {
  declare module.exports: $Exports<'firebase-tools/lib/init/features/index'>;
}
declare module 'firebase-tools/lib/init/features/project.js' {
  declare module.exports: $Exports<'firebase-tools/lib/init/features/project'>;
}
declare module 'firebase-tools/lib/init/features/storage.js' {
  declare module.exports: $Exports<'firebase-tools/lib/init/features/storage'>;
}
declare module 'firebase-tools/lib/init/index.js' {
  declare module.exports: $Exports<'firebase-tools/lib/init/index'>;
}
declare module 'firebase-tools/lib/listFiles.js' {
  declare module.exports: $Exports<'firebase-tools/lib/listFiles'>;
}
declare module 'firebase-tools/lib/loadCJSON.js' {
  declare module.exports: $Exports<'firebase-tools/lib/loadCJSON'>;
}
declare module 'firebase-tools/lib/loadRCFile.js' {
  declare module.exports: $Exports<'firebase-tools/lib/loadRCFile'>;
}
declare module 'firebase-tools/lib/logError.js' {
  declare module.exports: $Exports<'firebase-tools/lib/logError'>;
}
declare module 'firebase-tools/lib/logger.js' {
  declare module.exports: $Exports<'firebase-tools/lib/logger'>;
}
declare module 'firebase-tools/lib/parseBoltRules.js' {
  declare module.exports: $Exports<'firebase-tools/lib/parseBoltRules'>;
}
declare module 'firebase-tools/lib/parseTriggers.js' {
  declare module.exports: $Exports<'firebase-tools/lib/parseTriggers'>;
}
declare module 'firebase-tools/lib/prepareFunctionsUpload.js' {
  declare module.exports: $Exports<'firebase-tools/lib/prepareFunctionsUpload'>;
}
declare module 'firebase-tools/lib/prepareUpload.js' {
  declare module.exports: $Exports<'firebase-tools/lib/prepareUpload'>;
}
declare module 'firebase-tools/lib/previews.js' {
  declare module.exports: $Exports<'firebase-tools/lib/previews'>;
}
declare module 'firebase-tools/lib/profiler.js' {
  declare module.exports: $Exports<'firebase-tools/lib/profiler'>;
}
declare module 'firebase-tools/lib/profileReport.js' {
  declare module.exports: $Exports<'firebase-tools/lib/profileReport'>;
}
declare module 'firebase-tools/lib/prompt.js' {
  declare module.exports: $Exports<'firebase-tools/lib/prompt'>;
}
declare module 'firebase-tools/lib/requireAccess.js' {
  declare module.exports: $Exports<'firebase-tools/lib/requireAccess'>;
}
declare module 'firebase-tools/lib/requireAuth.js' {
  declare module.exports: $Exports<'firebase-tools/lib/requireAuth'>;
}
declare module 'firebase-tools/lib/requireConfig.js' {
  declare module.exports: $Exports<'firebase-tools/lib/requireConfig'>;
}
declare module 'firebase-tools/lib/resolveProjectPath.js' {
  declare module.exports: $Exports<'firebase-tools/lib/resolveProjectPath'>;
}
declare module 'firebase-tools/lib/responseToError.js' {
  declare module.exports: $Exports<'firebase-tools/lib/responseToError'>;
}
declare module 'firebase-tools/lib/scopes.js' {
  declare module.exports: $Exports<'firebase-tools/lib/scopes'>;
}
declare module 'firebase-tools/lib/serve/functions.js' {
  declare module.exports: $Exports<'firebase-tools/lib/serve/functions'>;
}
declare module 'firebase-tools/lib/serve/hosting.js' {
  declare module.exports: $Exports<'firebase-tools/lib/serve/hosting'>;
}
declare module 'firebase-tools/lib/serve/index.js' {
  declare module.exports: $Exports<'firebase-tools/lib/serve/index'>;
}
declare module 'firebase-tools/lib/track.js' {
  declare module.exports: $Exports<'firebase-tools/lib/track'>;
}
declare module 'firebase-tools/lib/triggerParser.js' {
  declare module.exports: $Exports<'firebase-tools/lib/triggerParser'>;
}
declare module 'firebase-tools/lib/utils.js' {
  declare module.exports: $Exports<'firebase-tools/lib/utils'>;
}
declare module 'firebase-tools/lib/validateJsonRules.js' {
  declare module.exports: $Exports<'firebase-tools/lib/validateJsonRules'>;
}
declare module 'firebase-tools/lib/validator.js' {
  declare module.exports: $Exports<'firebase-tools/lib/validator'>;
}
declare module 'firebase-tools/templates/hosting/init.js' {
  declare module.exports: $Exports<'firebase-tools/templates/hosting/init'>;
}
declare module 'firebase-tools/templates/init/functions/index.js' {
  declare module.exports: $Exports<'firebase-tools/templates/init/functions/index'>;
}
declare module 'firebase-tools/templates/setup/web.js' {
  declare module.exports: $Exports<'firebase-tools/templates/setup/web'>;
}
