// flow-typed signature: 414e47d2132c528d0f67069d1ef11c17
// flow-typed version: <<STUB>>/html-webpack-inline-source-plugin_v0.0.10/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html-webpack-inline-source-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'html-webpack-inline-source-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'html-webpack-inline-source-plugin/index' {
  declare module.exports: $Exports<'html-webpack-inline-source-plugin'>;
}
declare module 'html-webpack-inline-source-plugin/index.js' {
  declare module.exports: $Exports<'html-webpack-inline-source-plugin'>;
}
