// flow-typed signature: fbffcb92776837a68be1ba40d7d40a81
// flow-typed version: <<STUB>>/lighthouse_v^2.4.0/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lighthouse'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lighthouse' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lighthouse/chrome-launcher/ask' {
  declare module.exports: any;
}

declare module 'lighthouse/chrome-launcher/chrome-finder' {
  declare module.exports: any;
}

declare module 'lighthouse/chrome-launcher/chrome-launcher' {
  declare module.exports: any;
}

declare module 'lighthouse/chrome-launcher/compiled-check' {
  declare module.exports: any;
}

declare module 'lighthouse/chrome-launcher/flags' {
  declare module.exports: any;
}

declare module 'lighthouse/chrome-launcher/index' {
  declare module.exports: any;
}

declare module 'lighthouse/chrome-launcher/manual-chrome-launcher' {
  declare module.exports: any;
}

declare module 'lighthouse/chrome-launcher/random-port' {
  declare module.exports: any;
}

declare module 'lighthouse/chrome-launcher/utils' {
  declare module.exports: any;
}

declare module 'lighthouse/docs/recipes/custom-audit/custom-config' {
  declare module.exports: any;
}

declare module 'lighthouse/docs/recipes/custom-audit/searchable-audit' {
  declare module.exports: any;
}

declare module 'lighthouse/docs/recipes/custom-audit/searchable-gatherer' {
  declare module.exports: any;
}

declare module 'lighthouse/docs/recipes/gulp/gulpfile' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/bin' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/cli-flags' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/commands/commands' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/commands/list-audits' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/commands/list-trace-categories' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/compiled-check' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/index' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/performance-experiment/experiment-database/database' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/performance-experiment/report/perf-x-report-generator' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/performance-experiment/report/scripts/perf-x' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/performance-experiment/server' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/printer' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/run' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/shim-modules' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/cli/bin-test' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/cli/index-test' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/cli/performance-experiment/database-test' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/cli/printer-test' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/cli/run-test' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/fixtures/dobetterweb/dbw_tester' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/fixtures/offline-ready-sw' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/fixtures/static-server' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/global-mocha-hooks' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/smokehouse/byte-config' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/smokehouse/byte-efficiency/expectations' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/smokehouse/dbw-config' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/smokehouse/offline-config' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/smokehouse/offline-local/offline-expectations' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/smokehouse/perf/expectations' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/smokehouse/pwa-config' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/smokehouse/pwa-expectations' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/smokehouse/smokehouse' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/smokehouse/tricky-ttci/expectations' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/accesskeys' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/aria-allowed-attr' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/aria-required-attr' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/aria-required-children' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/aria-required-parent' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/aria-roles' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/aria-valid-attr-value' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/aria-valid-attr' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/audio-caption' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/axe-audit' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/button-name' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/bypass' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/color-contrast' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/definition-list' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/dlitem' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/document-title' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/duplicate-id' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/frame-title' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/html-has-lang' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/html-lang-valid' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/image-alt' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/input-image-alt' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/label' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/layout-table' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/link-name' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/list' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/listitem' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/meta-refresh' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/meta-viewport' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/object-alt' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/tabindex' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/td-headers-attr' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/th-has-data-cells' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/valid-lang' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/video-caption' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/video-description' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/audit' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/byte-efficiency-audit' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/offscreen-images' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/total-byte-weight' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/unused-css-rules' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/uses-optimized-images' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/uses-request-compression' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/uses-responsive-images' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/uses-webp-images' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/cache-start-url' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/consistently-interactive' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/content-width' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/critical-request-chains' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/deprecations' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/dobetterweb/appcache-manifest' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/dobetterweb/dom-size' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/dobetterweb/external-anchors-use-rel-noopener' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/dobetterweb/geolocation-on-start' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/dobetterweb/link-blocking-first-paint' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/dobetterweb/no-document-write' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/dobetterweb/no-mutation-events' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/dobetterweb/no-old-flexbox' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/dobetterweb/no-websql' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/dobetterweb/notification-on-start' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/dobetterweb/password-inputs-can-be-pasted-into' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/dobetterweb/script-blocking-first-paint' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/dobetterweb/uses-http2' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/dobetterweb/uses-passive-event-listeners' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/estimated-input-latency' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/first-interactive' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/first-meaningful-paint' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/is-on-https' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/load-fast-enough-for-pwa' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/manifest-short-name-length' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/manual/manual-audit' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/manual/pwa-cross-browser' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/manual/pwa-each-page-has-url' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/manual/pwa-page-transitions' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/multi-check-audit' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/redirects-http' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/screenshot-thumbnails' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/service-worker' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/speed-index-metric' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/splash-screen' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/themed-omnibox' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/time-to-firstbyte' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/user-timings' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/viewport' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/violation-audit' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/webapp-install-banner' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/without-javascript' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/works-offline' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/closure/closure-type-checking' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/closure/third_party/commonjs' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/closure/third_party/DevtoolsTimelineModel' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/closure/third_party/node' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/closure/third_party/WebInspector' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/closure/typedefs/Accessibility' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/closure/typedefs/Artifacts' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/closure/typedefs/Audit' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/closure/typedefs/AuditResult' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/closure/typedefs/ComputedArtifacts' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/closure/typedefs/Config' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/closure/typedefs/Manifest' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/closure/typedefs/ServiceWorkerArtifact' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/closure/typedefs/SpeedlineArtifact' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/closure/typedefs/Trace' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/closure/typedefs/viewer-externs' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/config/config' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/config/default' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/config/fast-config' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/config/full-config' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/config/plots-config' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/computed/computed-artifact' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/computed/critical-request-chains' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/computed/first-interactive' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/computed/manifest-values' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/computed/network-records' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/computed/network-throughput' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/computed/pushed-requests' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/computed/screenshots' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/computed/speedline' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/computed/trace-of-tab' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/connections/connection' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/connections/cri' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/connections/extension' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/connections/raw' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/devtools-log' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/driver' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gather-runner' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/accessibility' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/cache-contents' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/chrome-console-messages' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/css-usage' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/all-event-listeners' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/anchors-with-no-rel-noopener' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/appcache' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/domstats' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/optimized-images' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/password-inputs-with-prevented-paste' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/response-compression' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/tags-blocking-first-paint' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/websql' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/gatherer' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/html-without-javascript' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/http-redirect' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/image-usage' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/manifest' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/offline' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/service-worker' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/start-url' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/styles' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/theme-color' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/url' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/viewport-dimensions' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/viewport' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/index' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/asset-saver' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/console-quieter' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/dom-helpers' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/element' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/empty-stub' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/emulation' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/event-helpers' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/file-namer' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/icons' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/manifest-parser' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/network-recorder' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/statistics' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/styles-helpers' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/traces/devtools-timeline-model' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/traces/pwmetrics-events' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/traces/trace-parser' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/traces/tracing-processor' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/url-shim' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/web-inspector' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/report/v2/renderer/category-renderer' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/report/v2/renderer/crc-details-renderer' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/report/v2/renderer/details-renderer' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/report/v2/renderer/dom' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/report/v2/renderer/logger' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/report/v2/renderer/report-renderer' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/report/v2/renderer/report-ui-features' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/report/v2/renderer/util' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/report/v2/report-generator' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/runner' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-logger/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lighthouse/chrome-launcher/ask.js' {
  declare module.exports: $Exports<'lighthouse/chrome-launcher/ask'>;
}
declare module 'lighthouse/chrome-launcher/chrome-finder.js' {
  declare module.exports: $Exports<'lighthouse/chrome-launcher/chrome-finder'>;
}
declare module 'lighthouse/chrome-launcher/chrome-launcher.js' {
  declare module.exports: $Exports<'lighthouse/chrome-launcher/chrome-launcher'>;
}
declare module 'lighthouse/chrome-launcher/compiled-check.js' {
  declare module.exports: $Exports<'lighthouse/chrome-launcher/compiled-check'>;
}
declare module 'lighthouse/chrome-launcher/flags.js' {
  declare module.exports: $Exports<'lighthouse/chrome-launcher/flags'>;
}
declare module 'lighthouse/chrome-launcher/index.js' {
  declare module.exports: $Exports<'lighthouse/chrome-launcher/index'>;
}
declare module 'lighthouse/chrome-launcher/manual-chrome-launcher.js' {
  declare module.exports: $Exports<'lighthouse/chrome-launcher/manual-chrome-launcher'>;
}
declare module 'lighthouse/chrome-launcher/random-port.js' {
  declare module.exports: $Exports<'lighthouse/chrome-launcher/random-port'>;
}
declare module 'lighthouse/chrome-launcher/utils.js' {
  declare module.exports: $Exports<'lighthouse/chrome-launcher/utils'>;
}
declare module 'lighthouse/docs/recipes/custom-audit/custom-config.js' {
  declare module.exports: $Exports<'lighthouse/docs/recipes/custom-audit/custom-config'>;
}
declare module 'lighthouse/docs/recipes/custom-audit/searchable-audit.js' {
  declare module.exports: $Exports<'lighthouse/docs/recipes/custom-audit/searchable-audit'>;
}
declare module 'lighthouse/docs/recipes/custom-audit/searchable-gatherer.js' {
  declare module.exports: $Exports<'lighthouse/docs/recipes/custom-audit/searchable-gatherer'>;
}
declare module 'lighthouse/docs/recipes/gulp/gulpfile.js' {
  declare module.exports: $Exports<'lighthouse/docs/recipes/gulp/gulpfile'>;
}
declare module 'lighthouse/lighthouse-cli/bin.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/bin'>;
}
declare module 'lighthouse/lighthouse-cli/cli-flags.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/cli-flags'>;
}
declare module 'lighthouse/lighthouse-cli/commands/commands.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/commands/commands'>;
}
declare module 'lighthouse/lighthouse-cli/commands/list-audits.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/commands/list-audits'>;
}
declare module 'lighthouse/lighthouse-cli/commands/list-trace-categories.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/commands/list-trace-categories'>;
}
declare module 'lighthouse/lighthouse-cli/compiled-check.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/compiled-check'>;
}
declare module 'lighthouse/lighthouse-cli/index.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/index'>;
}
declare module 'lighthouse/lighthouse-cli/performance-experiment/experiment-database/database.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/performance-experiment/experiment-database/database'>;
}
declare module 'lighthouse/lighthouse-cli/performance-experiment/report/perf-x-report-generator.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/performance-experiment/report/perf-x-report-generator'>;
}
declare module 'lighthouse/lighthouse-cli/performance-experiment/report/scripts/perf-x.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/performance-experiment/report/scripts/perf-x'>;
}
declare module 'lighthouse/lighthouse-cli/performance-experiment/server.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/performance-experiment/server'>;
}
declare module 'lighthouse/lighthouse-cli/printer.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/printer'>;
}
declare module 'lighthouse/lighthouse-cli/run.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/run'>;
}
declare module 'lighthouse/lighthouse-cli/shim-modules.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/shim-modules'>;
}
declare module 'lighthouse/lighthouse-cli/test/cli/bin-test.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/cli/bin-test'>;
}
declare module 'lighthouse/lighthouse-cli/test/cli/index-test.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/cli/index-test'>;
}
declare module 'lighthouse/lighthouse-cli/test/cli/performance-experiment/database-test.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/cli/performance-experiment/database-test'>;
}
declare module 'lighthouse/lighthouse-cli/test/cli/printer-test.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/cli/printer-test'>;
}
declare module 'lighthouse/lighthouse-cli/test/cli/run-test.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/cli/run-test'>;
}
declare module 'lighthouse/lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/fixtures/dobetterweb/dbw_tester'>;
}
declare module 'lighthouse/lighthouse-cli/test/fixtures/offline-ready-sw.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/fixtures/offline-ready-sw'>;
}
declare module 'lighthouse/lighthouse-cli/test/fixtures/static-server.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/fixtures/static-server'>;
}
declare module 'lighthouse/lighthouse-cli/test/global-mocha-hooks.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/global-mocha-hooks'>;
}
declare module 'lighthouse/lighthouse-cli/test/smokehouse/byte-config.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/smokehouse/byte-config'>;
}
declare module 'lighthouse/lighthouse-cli/test/smokehouse/byte-efficiency/expectations.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/smokehouse/byte-efficiency/expectations'>;
}
declare module 'lighthouse/lighthouse-cli/test/smokehouse/dbw-config.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/smokehouse/dbw-config'>;
}
declare module 'lighthouse/lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations'>;
}
declare module 'lighthouse/lighthouse-cli/test/smokehouse/offline-config.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/smokehouse/offline-config'>;
}
declare module 'lighthouse/lighthouse-cli/test/smokehouse/offline-local/offline-expectations.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/smokehouse/offline-local/offline-expectations'>;
}
declare module 'lighthouse/lighthouse-cli/test/smokehouse/perf/expectations.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/smokehouse/perf/expectations'>;
}
declare module 'lighthouse/lighthouse-cli/test/smokehouse/pwa-config.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/smokehouse/pwa-config'>;
}
declare module 'lighthouse/lighthouse-cli/test/smokehouse/pwa-expectations.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/smokehouse/pwa-expectations'>;
}
declare module 'lighthouse/lighthouse-cli/test/smokehouse/smokehouse.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/smokehouse/smokehouse'>;
}
declare module 'lighthouse/lighthouse-cli/test/smokehouse/tricky-ttci/expectations.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/smokehouse/tricky-ttci/expectations'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/accesskeys.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/accesskeys'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/aria-allowed-attr.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/aria-allowed-attr'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/aria-required-attr.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/aria-required-attr'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/aria-required-children.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/aria-required-children'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/aria-required-parent.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/aria-required-parent'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/aria-roles.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/aria-roles'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/aria-valid-attr-value.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/aria-valid-attr-value'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/aria-valid-attr.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/aria-valid-attr'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/audio-caption.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/audio-caption'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/axe-audit.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/axe-audit'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/button-name.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/button-name'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/bypass.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/bypass'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/color-contrast.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/color-contrast'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/definition-list.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/definition-list'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/dlitem.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/dlitem'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/document-title.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/document-title'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/duplicate-id.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/duplicate-id'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/frame-title.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/frame-title'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/html-has-lang.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/html-has-lang'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/html-lang-valid.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/html-lang-valid'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/image-alt.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/image-alt'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/input-image-alt.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/input-image-alt'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/label.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/label'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/layout-table.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/layout-table'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/link-name.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/link-name'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/list.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/list'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/listitem.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/listitem'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/meta-refresh.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/meta-refresh'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/meta-viewport.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/meta-viewport'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/object-alt.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/object-alt'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/tabindex.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/tabindex'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/td-headers-attr.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/td-headers-attr'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/th-has-data-cells.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/th-has-data-cells'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/valid-lang.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/valid-lang'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/video-caption.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/video-caption'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/video-description.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/video-description'>;
}
declare module 'lighthouse/lighthouse-core/audits/audit.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/audit'>;
}
declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/byte-efficiency/byte-efficiency-audit'>;
}
declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/offscreen-images.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/byte-efficiency/offscreen-images'>;
}
declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/total-byte-weight.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/byte-efficiency/total-byte-weight'>;
}
declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/unused-css-rules.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/byte-efficiency/unused-css-rules'>;
}
declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/uses-optimized-images.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/byte-efficiency/uses-optimized-images'>;
}
declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/uses-request-compression.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/byte-efficiency/uses-request-compression'>;
}
declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/uses-responsive-images.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/byte-efficiency/uses-responsive-images'>;
}
declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/uses-webp-images.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/byte-efficiency/uses-webp-images'>;
}
declare module 'lighthouse/lighthouse-core/audits/cache-start-url.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/cache-start-url'>;
}
declare module 'lighthouse/lighthouse-core/audits/consistently-interactive.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/consistently-interactive'>;
}
declare module 'lighthouse/lighthouse-core/audits/content-width.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/content-width'>;
}
declare module 'lighthouse/lighthouse-core/audits/critical-request-chains.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/critical-request-chains'>;
}
declare module 'lighthouse/lighthouse-core/audits/deprecations.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/deprecations'>;
}
declare module 'lighthouse/lighthouse-core/audits/dobetterweb/appcache-manifest.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/dobetterweb/appcache-manifest'>;
}
declare module 'lighthouse/lighthouse-core/audits/dobetterweb/dom-size.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/dobetterweb/dom-size'>;
}
declare module 'lighthouse/lighthouse-core/audits/dobetterweb/external-anchors-use-rel-noopener.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/dobetterweb/external-anchors-use-rel-noopener'>;
}
declare module 'lighthouse/lighthouse-core/audits/dobetterweb/geolocation-on-start.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/dobetterweb/geolocation-on-start'>;
}
declare module 'lighthouse/lighthouse-core/audits/dobetterweb/link-blocking-first-paint.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/dobetterweb/link-blocking-first-paint'>;
}
declare module 'lighthouse/lighthouse-core/audits/dobetterweb/no-document-write.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/dobetterweb/no-document-write'>;
}
declare module 'lighthouse/lighthouse-core/audits/dobetterweb/no-mutation-events.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/dobetterweb/no-mutation-events'>;
}
declare module 'lighthouse/lighthouse-core/audits/dobetterweb/no-old-flexbox.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/dobetterweb/no-old-flexbox'>;
}
declare module 'lighthouse/lighthouse-core/audits/dobetterweb/no-websql.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/dobetterweb/no-websql'>;
}
declare module 'lighthouse/lighthouse-core/audits/dobetterweb/notification-on-start.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/dobetterweb/notification-on-start'>;
}
declare module 'lighthouse/lighthouse-core/audits/dobetterweb/password-inputs-can-be-pasted-into.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/dobetterweb/password-inputs-can-be-pasted-into'>;
}
declare module 'lighthouse/lighthouse-core/audits/dobetterweb/script-blocking-first-paint.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/dobetterweb/script-blocking-first-paint'>;
}
declare module 'lighthouse/lighthouse-core/audits/dobetterweb/uses-http2.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/dobetterweb/uses-http2'>;
}
declare module 'lighthouse/lighthouse-core/audits/dobetterweb/uses-passive-event-listeners.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/dobetterweb/uses-passive-event-listeners'>;
}
declare module 'lighthouse/lighthouse-core/audits/estimated-input-latency.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/estimated-input-latency'>;
}
declare module 'lighthouse/lighthouse-core/audits/first-interactive.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/first-interactive'>;
}
declare module 'lighthouse/lighthouse-core/audits/first-meaningful-paint.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/first-meaningful-paint'>;
}
declare module 'lighthouse/lighthouse-core/audits/is-on-https.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/is-on-https'>;
}
declare module 'lighthouse/lighthouse-core/audits/load-fast-enough-for-pwa.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/load-fast-enough-for-pwa'>;
}
declare module 'lighthouse/lighthouse-core/audits/manifest-short-name-length.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/manifest-short-name-length'>;
}
declare module 'lighthouse/lighthouse-core/audits/manual/manual-audit.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/manual/manual-audit'>;
}
declare module 'lighthouse/lighthouse-core/audits/manual/pwa-cross-browser.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/manual/pwa-cross-browser'>;
}
declare module 'lighthouse/lighthouse-core/audits/manual/pwa-each-page-has-url.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/manual/pwa-each-page-has-url'>;
}
declare module 'lighthouse/lighthouse-core/audits/manual/pwa-page-transitions.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/manual/pwa-page-transitions'>;
}
declare module 'lighthouse/lighthouse-core/audits/multi-check-audit.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/multi-check-audit'>;
}
declare module 'lighthouse/lighthouse-core/audits/redirects-http.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/redirects-http'>;
}
declare module 'lighthouse/lighthouse-core/audits/screenshot-thumbnails.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/screenshot-thumbnails'>;
}
declare module 'lighthouse/lighthouse-core/audits/service-worker.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/service-worker'>;
}
declare module 'lighthouse/lighthouse-core/audits/speed-index-metric.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/speed-index-metric'>;
}
declare module 'lighthouse/lighthouse-core/audits/splash-screen.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/splash-screen'>;
}
declare module 'lighthouse/lighthouse-core/audits/themed-omnibox.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/themed-omnibox'>;
}
declare module 'lighthouse/lighthouse-core/audits/time-to-firstbyte.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/time-to-firstbyte'>;
}
declare module 'lighthouse/lighthouse-core/audits/user-timings.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/user-timings'>;
}
declare module 'lighthouse/lighthouse-core/audits/viewport.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/viewport'>;
}
declare module 'lighthouse/lighthouse-core/audits/violation-audit.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/violation-audit'>;
}
declare module 'lighthouse/lighthouse-core/audits/webapp-install-banner.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/webapp-install-banner'>;
}
declare module 'lighthouse/lighthouse-core/audits/without-javascript.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/without-javascript'>;
}
declare module 'lighthouse/lighthouse-core/audits/works-offline.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/works-offline'>;
}
declare module 'lighthouse/lighthouse-core/closure/closure-type-checking.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/closure/closure-type-checking'>;
}
declare module 'lighthouse/lighthouse-core/closure/third_party/commonjs.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/closure/third_party/commonjs'>;
}
declare module 'lighthouse/lighthouse-core/closure/third_party/DevtoolsTimelineModel.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/closure/third_party/DevtoolsTimelineModel'>;
}
declare module 'lighthouse/lighthouse-core/closure/third_party/node.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/closure/third_party/node'>;
}
declare module 'lighthouse/lighthouse-core/closure/third_party/WebInspector.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/closure/third_party/WebInspector'>;
}
declare module 'lighthouse/lighthouse-core/closure/typedefs/Accessibility.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/closure/typedefs/Accessibility'>;
}
declare module 'lighthouse/lighthouse-core/closure/typedefs/Artifacts.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/closure/typedefs/Artifacts'>;
}
declare module 'lighthouse/lighthouse-core/closure/typedefs/Audit.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/closure/typedefs/Audit'>;
}
declare module 'lighthouse/lighthouse-core/closure/typedefs/AuditResult.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/closure/typedefs/AuditResult'>;
}
declare module 'lighthouse/lighthouse-core/closure/typedefs/ComputedArtifacts.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/closure/typedefs/ComputedArtifacts'>;
}
declare module 'lighthouse/lighthouse-core/closure/typedefs/Config.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/closure/typedefs/Config'>;
}
declare module 'lighthouse/lighthouse-core/closure/typedefs/Manifest.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/closure/typedefs/Manifest'>;
}
declare module 'lighthouse/lighthouse-core/closure/typedefs/ServiceWorkerArtifact.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/closure/typedefs/ServiceWorkerArtifact'>;
}
declare module 'lighthouse/lighthouse-core/closure/typedefs/SpeedlineArtifact.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/closure/typedefs/SpeedlineArtifact'>;
}
declare module 'lighthouse/lighthouse-core/closure/typedefs/Trace.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/closure/typedefs/Trace'>;
}
declare module 'lighthouse/lighthouse-core/closure/typedefs/viewer-externs.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/closure/typedefs/viewer-externs'>;
}
declare module 'lighthouse/lighthouse-core/config/config.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/config/config'>;
}
declare module 'lighthouse/lighthouse-core/config/default.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/config/default'>;
}
declare module 'lighthouse/lighthouse-core/config/fast-config.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/config/fast-config'>;
}
declare module 'lighthouse/lighthouse-core/config/full-config.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/config/full-config'>;
}
declare module 'lighthouse/lighthouse-core/config/plots-config.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/config/plots-config'>;
}
declare module 'lighthouse/lighthouse-core/gather/computed/computed-artifact.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/computed/computed-artifact'>;
}
declare module 'lighthouse/lighthouse-core/gather/computed/critical-request-chains.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/computed/critical-request-chains'>;
}
declare module 'lighthouse/lighthouse-core/gather/computed/first-interactive.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/computed/first-interactive'>;
}
declare module 'lighthouse/lighthouse-core/gather/computed/manifest-values.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/computed/manifest-values'>;
}
declare module 'lighthouse/lighthouse-core/gather/computed/network-records.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/computed/network-records'>;
}
declare module 'lighthouse/lighthouse-core/gather/computed/network-throughput.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/computed/network-throughput'>;
}
declare module 'lighthouse/lighthouse-core/gather/computed/pushed-requests.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/computed/pushed-requests'>;
}
declare module 'lighthouse/lighthouse-core/gather/computed/screenshots.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/computed/screenshots'>;
}
declare module 'lighthouse/lighthouse-core/gather/computed/speedline.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/computed/speedline'>;
}
declare module 'lighthouse/lighthouse-core/gather/computed/trace-of-tab.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/computed/trace-of-tab'>;
}
declare module 'lighthouse/lighthouse-core/gather/connections/connection.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/connections/connection'>;
}
declare module 'lighthouse/lighthouse-core/gather/connections/cri.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/connections/cri'>;
}
declare module 'lighthouse/lighthouse-core/gather/connections/extension.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/connections/extension'>;
}
declare module 'lighthouse/lighthouse-core/gather/connections/raw.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/connections/raw'>;
}
declare module 'lighthouse/lighthouse-core/gather/devtools-log.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/devtools-log'>;
}
declare module 'lighthouse/lighthouse-core/gather/driver.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/driver'>;
}
declare module 'lighthouse/lighthouse-core/gather/gather-runner.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gather-runner'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/accessibility.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/accessibility'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/cache-contents.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/cache-contents'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/chrome-console-messages.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/chrome-console-messages'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/css-usage.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/css-usage'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/all-event-listeners.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/all-event-listeners'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/anchors-with-no-rel-noopener.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/anchors-with-no-rel-noopener'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/appcache.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/appcache'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/domstats.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/domstats'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/optimized-images.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/optimized-images'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/password-inputs-with-prevented-paste.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/password-inputs-with-prevented-paste'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/response-compression.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/response-compression'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/tags-blocking-first-paint.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/tags-blocking-first-paint'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/websql.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/websql'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/gatherer.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/gatherer'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/html-without-javascript.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/html-without-javascript'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/http-redirect.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/http-redirect'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/image-usage.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/image-usage'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/manifest.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/manifest'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/offline.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/offline'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/service-worker.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/service-worker'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/start-url.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/start-url'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/styles.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/styles'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/theme-color.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/theme-color'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/url.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/url'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/viewport-dimensions.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/viewport-dimensions'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/viewport.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/viewport'>;
}
declare module 'lighthouse/lighthouse-core/index.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/index'>;
}
declare module 'lighthouse/lighthouse-core/lib/asset-saver.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/asset-saver'>;
}
declare module 'lighthouse/lighthouse-core/lib/console-quieter.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/console-quieter'>;
}
declare module 'lighthouse/lighthouse-core/lib/dom-helpers.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/dom-helpers'>;
}
declare module 'lighthouse/lighthouse-core/lib/element.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/element'>;
}
declare module 'lighthouse/lighthouse-core/lib/empty-stub.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/empty-stub'>;
}
declare module 'lighthouse/lighthouse-core/lib/emulation.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/emulation'>;
}
declare module 'lighthouse/lighthouse-core/lib/event-helpers.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/event-helpers'>;
}
declare module 'lighthouse/lighthouse-core/lib/file-namer.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/file-namer'>;
}
declare module 'lighthouse/lighthouse-core/lib/icons.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/icons'>;
}
declare module 'lighthouse/lighthouse-core/lib/manifest-parser.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/manifest-parser'>;
}
declare module 'lighthouse/lighthouse-core/lib/network-recorder.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/network-recorder'>;
}
declare module 'lighthouse/lighthouse-core/lib/statistics.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/statistics'>;
}
declare module 'lighthouse/lighthouse-core/lib/styles-helpers.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/styles-helpers'>;
}
declare module 'lighthouse/lighthouse-core/lib/traces/devtools-timeline-model.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/traces/devtools-timeline-model'>;
}
declare module 'lighthouse/lighthouse-core/lib/traces/pwmetrics-events.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/traces/pwmetrics-events'>;
}
declare module 'lighthouse/lighthouse-core/lib/traces/trace-parser.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/traces/trace-parser'>;
}
declare module 'lighthouse/lighthouse-core/lib/traces/tracing-processor.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/traces/tracing-processor'>;
}
declare module 'lighthouse/lighthouse-core/lib/url-shim.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/url-shim'>;
}
declare module 'lighthouse/lighthouse-core/lib/web-inspector.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/web-inspector'>;
}
declare module 'lighthouse/lighthouse-core/report/v2/renderer/category-renderer.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/report/v2/renderer/category-renderer'>;
}
declare module 'lighthouse/lighthouse-core/report/v2/renderer/crc-details-renderer.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/report/v2/renderer/crc-details-renderer'>;
}
declare module 'lighthouse/lighthouse-core/report/v2/renderer/details-renderer.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/report/v2/renderer/details-renderer'>;
}
declare module 'lighthouse/lighthouse-core/report/v2/renderer/dom.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/report/v2/renderer/dom'>;
}
declare module 'lighthouse/lighthouse-core/report/v2/renderer/logger.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/report/v2/renderer/logger'>;
}
declare module 'lighthouse/lighthouse-core/report/v2/renderer/report-renderer.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/report/v2/renderer/report-renderer'>;
}
declare module 'lighthouse/lighthouse-core/report/v2/renderer/report-ui-features.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/report/v2/renderer/report-ui-features'>;
}
declare module 'lighthouse/lighthouse-core/report/v2/renderer/util.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/report/v2/renderer/util'>;
}
declare module 'lighthouse/lighthouse-core/report/v2/report-generator.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/report/v2/report-generator'>;
}
declare module 'lighthouse/lighthouse-core/runner.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/runner'>;
}
declare module 'lighthouse/lighthouse-logger/index.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-logger/index'>;
}
