// flow-typed signature: 6d3840d098eb6b2761b925c935297557
// flow-typed version: <<STUB>>/optimize-css-assets-webpack-plugin_v4.0.1/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'optimize-css-assets-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'optimize-css-assets-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'optimize-css-assets-webpack-plugin/src/index' {
  declare module.exports: any;
}

declare module 'optimize-css-assets-webpack-plugin/test/cases/assetNameRegExp-no-source/index' {
  declare module.exports: any;
}

declare module 'optimize-css-assets-webpack-plugin/test/cases/assetNameRegExp-no-source/webpack.config' {
  declare module.exports: any;
}

declare module 'optimize-css-assets-webpack-plugin/test/cases/duplicate-css-exists-without-plugin/index' {
  declare module.exports: any;
}

declare module 'optimize-css-assets-webpack-plugin/test/cases/duplicate-css-exists-without-plugin/webpack.config' {
  declare module.exports: any;
}

declare module 'optimize-css-assets-webpack-plugin/test/cases/only-assetNameRegExp-processed/index' {
  declare module.exports: any;
}

declare module 'optimize-css-assets-webpack-plugin/test/cases/only-assetNameRegExp-processed/webpack.config' {
  declare module.exports: any;
}

declare module 'optimize-css-assets-webpack-plugin/test/cases/removes-duplicate-css/index' {
  declare module.exports: any;
}

declare module 'optimize-css-assets-webpack-plugin/test/cases/removes-duplicate-css/webpack.config' {
  declare module.exports: any;
}

declare module 'optimize-css-assets-webpack-plugin/test/plugin.test' {
  declare module.exports: any;
}

declare module 'optimize-css-assets-webpack-plugin/test/util/helpers' {
  declare module.exports: any;
}

declare module 'optimize-css-assets-webpack-plugin/test/util/index' {
  declare module.exports: any;
}

declare module 'optimize-css-assets-webpack-plugin/test/webpack-integration.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'optimize-css-assets-webpack-plugin/src/index.js' {
  declare module.exports: $Exports<'optimize-css-assets-webpack-plugin/src/index'>;
}
declare module 'optimize-css-assets-webpack-plugin/test/cases/assetNameRegExp-no-source/index.js' {
  declare module.exports: $Exports<'optimize-css-assets-webpack-plugin/test/cases/assetNameRegExp-no-source/index'>;
}
declare module 'optimize-css-assets-webpack-plugin/test/cases/assetNameRegExp-no-source/webpack.config.js' {
  declare module.exports: $Exports<'optimize-css-assets-webpack-plugin/test/cases/assetNameRegExp-no-source/webpack.config'>;
}
declare module 'optimize-css-assets-webpack-plugin/test/cases/duplicate-css-exists-without-plugin/index.js' {
  declare module.exports: $Exports<'optimize-css-assets-webpack-plugin/test/cases/duplicate-css-exists-without-plugin/index'>;
}
declare module 'optimize-css-assets-webpack-plugin/test/cases/duplicate-css-exists-without-plugin/webpack.config.js' {
  declare module.exports: $Exports<'optimize-css-assets-webpack-plugin/test/cases/duplicate-css-exists-without-plugin/webpack.config'>;
}
declare module 'optimize-css-assets-webpack-plugin/test/cases/only-assetNameRegExp-processed/index.js' {
  declare module.exports: $Exports<'optimize-css-assets-webpack-plugin/test/cases/only-assetNameRegExp-processed/index'>;
}
declare module 'optimize-css-assets-webpack-plugin/test/cases/only-assetNameRegExp-processed/webpack.config.js' {
  declare module.exports: $Exports<'optimize-css-assets-webpack-plugin/test/cases/only-assetNameRegExp-processed/webpack.config'>;
}
declare module 'optimize-css-assets-webpack-plugin/test/cases/removes-duplicate-css/index.js' {
  declare module.exports: $Exports<'optimize-css-assets-webpack-plugin/test/cases/removes-duplicate-css/index'>;
}
declare module 'optimize-css-assets-webpack-plugin/test/cases/removes-duplicate-css/webpack.config.js' {
  declare module.exports: $Exports<'optimize-css-assets-webpack-plugin/test/cases/removes-duplicate-css/webpack.config'>;
}
declare module 'optimize-css-assets-webpack-plugin/test/plugin.test.js' {
  declare module.exports: $Exports<'optimize-css-assets-webpack-plugin/test/plugin.test'>;
}
declare module 'optimize-css-assets-webpack-plugin/test/util/helpers.js' {
  declare module.exports: $Exports<'optimize-css-assets-webpack-plugin/test/util/helpers'>;
}
declare module 'optimize-css-assets-webpack-plugin/test/util/index.js' {
  declare module.exports: $Exports<'optimize-css-assets-webpack-plugin/test/util/index'>;
}
declare module 'optimize-css-assets-webpack-plugin/test/webpack-integration.test.js' {
  declare module.exports: $Exports<'optimize-css-assets-webpack-plugin/test/webpack-integration.test'>;
}
