// flow-typed signature: c07c72f7b3f1150c4927daac62c52328
// flow-typed version: <<STUB>>/preload-webpack-plugin_v^1.2.3/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'preload-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'preload-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'preload-webpack-plugin/index' {
  declare module.exports: $Exports<'preload-webpack-plugin'>;
}
declare module 'preload-webpack-plugin/index.js' {
  declare module.exports: $Exports<'preload-webpack-plugin'>;
}
