// flow-typed signature: e5f091b2cc01bd720990cde9fed25a9d
// flow-typed version: <<STUB>>/preload-webpack-plugin_v3.0.0-beta.1/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'preload-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'preload-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'preload-webpack-plugin/build/index' {
  declare module.exports: any;
}

declare module 'preload-webpack-plugin/build/lib/create-html-element-string' {
  declare module.exports: any;
}

declare module 'preload-webpack-plugin/build/lib/default-options' {
  declare module.exports: any;
}

declare module 'preload-webpack-plugin/build/lib/determine-as-value' {
  declare module.exports: any;
}

declare module 'preload-webpack-plugin/build/lib/does-chunk-belong-to-html' {
  declare module.exports: any;
}

declare module 'preload-webpack-plugin/build/lib/extract-chunks' {
  declare module.exports: any;
}

declare module 'preload-webpack-plugin/build/lib/insert-links-into-head' {
  declare module.exports: any;
}

// Filename aliases
declare module 'preload-webpack-plugin/build/index.js' {
  declare module.exports: $Exports<'preload-webpack-plugin/build/index'>;
}
declare module 'preload-webpack-plugin/build/lib/create-html-element-string.js' {
  declare module.exports: $Exports<'preload-webpack-plugin/build/lib/create-html-element-string'>;
}
declare module 'preload-webpack-plugin/build/lib/default-options.js' {
  declare module.exports: $Exports<'preload-webpack-plugin/build/lib/default-options'>;
}
declare module 'preload-webpack-plugin/build/lib/determine-as-value.js' {
  declare module.exports: $Exports<'preload-webpack-plugin/build/lib/determine-as-value'>;
}
declare module 'preload-webpack-plugin/build/lib/does-chunk-belong-to-html.js' {
  declare module.exports: $Exports<'preload-webpack-plugin/build/lib/does-chunk-belong-to-html'>;
}
declare module 'preload-webpack-plugin/build/lib/extract-chunks.js' {
  declare module.exports: $Exports<'preload-webpack-plugin/build/lib/extract-chunks'>;
}
declare module 'preload-webpack-plugin/build/lib/insert-links-into-head.js' {
  declare module.exports: $Exports<'preload-webpack-plugin/build/lib/insert-links-into-head'>;
}
