// flow-typed signature: fe0c0cc362fe3877c87d6762b58be4b8
// flow-typed version: <<STUB>>/redux-thunk_v2.2.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-thunk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-thunk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-thunk/dist/redux-thunk' {
  declare module.exports: any;
}

declare module 'redux-thunk/dist/redux-thunk.min' {
  declare module.exports: any;
}

declare module 'redux-thunk/es/index' {
  declare module.exports: any;
}

declare module 'redux-thunk/lib/index' {
  declare module.exports: any;
}

declare module 'redux-thunk/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-thunk/dist/redux-thunk.js' {
  declare module.exports: $Exports<'redux-thunk/dist/redux-thunk'>;
}
declare module 'redux-thunk/dist/redux-thunk.min.js' {
  declare module.exports: $Exports<'redux-thunk/dist/redux-thunk.min'>;
}
declare module 'redux-thunk/es/index.js' {
  declare module.exports: $Exports<'redux-thunk/es/index'>;
}
declare module 'redux-thunk/lib/index.js' {
  declare module.exports: $Exports<'redux-thunk/lib/index'>;
}
declare module 'redux-thunk/src/index.js' {
  declare module.exports: $Exports<'redux-thunk/src/index'>;
}
