// flow-typed signature: d8d9a1e4a3348d5f511954cc30a17061
// flow-typed version: <<STUB>>/sw-precache-webpack-plugin_v^0.11.5/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sw-precache-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sw-precache-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sw-precache-webpack-plugin/lib/index' {
  declare module.exports: any;
}

declare module 'sw-precache-webpack-plugin/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sw-precache-webpack-plugin/lib/index.js' {
  declare module.exports: $Exports<'sw-precache-webpack-plugin/lib/index'>;
}
declare module 'sw-precache-webpack-plugin/src/index.js' {
  declare module.exports: $Exports<'sw-precache-webpack-plugin/src/index'>;
}
