// flow-typed signature: 0b82649c6367055c387e94c4a70ec395
// flow-typed version: <<STUB>>/thread-loader_v^1.1.1/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'thread-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'thread-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'thread-loader/dist/cjs' {
  declare module.exports: any;
}

declare module 'thread-loader/dist/index' {
  declare module.exports: any;
}

declare module 'thread-loader/dist/readBuffer' {
  declare module.exports: any;
}

declare module 'thread-loader/dist/worker' {
  declare module.exports: any;
}

declare module 'thread-loader/dist/WorkerPool' {
  declare module.exports: any;
}

declare module 'thread-loader/dist/workerPools' {
  declare module.exports: any;
}

// Filename aliases
declare module 'thread-loader/dist/cjs.js' {
  declare module.exports: $Exports<'thread-loader/dist/cjs'>;
}
declare module 'thread-loader/dist/index.js' {
  declare module.exports: $Exports<'thread-loader/dist/index'>;
}
declare module 'thread-loader/dist/readBuffer.js' {
  declare module.exports: $Exports<'thread-loader/dist/readBuffer'>;
}
declare module 'thread-loader/dist/worker.js' {
  declare module.exports: $Exports<'thread-loader/dist/worker'>;
}
declare module 'thread-loader/dist/WorkerPool.js' {
  declare module.exports: $Exports<'thread-loader/dist/WorkerPool'>;
}
declare module 'thread-loader/dist/workerPools.js' {
  declare module.exports: $Exports<'thread-loader/dist/workerPools'>;
}
