// flow-typed signature: f75847421c3699ce5781b68c6b72279e
// flow-typed version: <<STUB>>/uglify-js_vgit://github.com/mishoo/UglifyJS2#harmony/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uglify-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uglify-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'uglify-js/bin/extract-props' {
  declare module.exports: any;
}

declare module 'uglify-js/lib/ast' {
  declare module.exports: any;
}

declare module 'uglify-js/lib/compress' {
  declare module.exports: any;
}

declare module 'uglify-js/lib/mozilla-ast' {
  declare module.exports: any;
}

declare module 'uglify-js/lib/output' {
  declare module.exports: any;
}

declare module 'uglify-js/lib/parse' {
  declare module.exports: any;
}

declare module 'uglify-js/lib/propmangle' {
  declare module.exports: any;
}

declare module 'uglify-js/lib/scope' {
  declare module.exports: any;
}

declare module 'uglify-js/lib/sourcemap' {
  declare module.exports: any;
}

declare module 'uglify-js/lib/transform' {
  declare module.exports: any;
}

declare module 'uglify-js/lib/utils' {
  declare module.exports: any;
}

declare module 'uglify-js/test/benchmark' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/angular-inject' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/arrays' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/arrow' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/ascii' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/asm' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/assignment' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/block-scope' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/blocks' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/collapse_vars' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/comparing' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/concat-strings' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/conditionals' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/const' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/dead-code' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/debugger' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/destructuring' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/directives' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/drop-console' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/drop-unused' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/evaluate' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/expansions' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/expression' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/functions' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/global_defs' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/harmony' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/hoist_vars' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/hoist' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/html_comments' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/if_return' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-1001' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-1034' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-1041' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-1043' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-1044' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-1052' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-1105' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-12' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-1202' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-1212' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-126' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-1261' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-1275' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-1321' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-143' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-1431' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-1443' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-1446' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-1447' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-1466' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-1569' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-1588' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-1609' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-1639' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-1656' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-1673' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-1704' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-1733' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-1750' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-1770' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-1787' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-203' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-208' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-22' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-267' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-269' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-368' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-44' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-59' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-597' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-611' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-637' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-640' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-747' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-751' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-782' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-892' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-913' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-926' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-973' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-976' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/issue-979' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/join-vars' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/labels' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/loops' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/max_line_len' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/negate-iife' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/new' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/numbers' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/object' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/parameters' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/properties' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/pure_funcs' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/pure_getters' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/reduce_vars' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/return_undefined' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/screw-ie8' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/sequences' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/string-literal' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/super' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/switch' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/template-string' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/transform' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/try-catch' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/typeof' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/unicode' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/wrap_iife' {
  declare module.exports: any;
}

declare module 'uglify-js/test/compress/yield' {
  declare module.exports: any;
}

declare module 'uglify-js/test/input/comments/filter' {
  declare module.exports: any;
}

declare module 'uglify-js/test/input/global_defs/nested' {
  declare module.exports: any;
}

declare module 'uglify-js/test/input/global_defs/simple' {
  declare module.exports: any;
}

declare module 'uglify-js/test/input/invalid/assign_1' {
  declare module.exports: any;
}

declare module 'uglify-js/test/input/invalid/assign_2' {
  declare module.exports: any;
}

declare module 'uglify-js/test/input/invalid/assign_3' {
  declare module.exports: any;
}

declare module 'uglify-js/test/input/invalid/eof' {
  declare module.exports: any;
}

declare module 'uglify-js/test/input/invalid/loop-no-body' {
  declare module.exports: any;
}

declare module 'uglify-js/test/input/invalid/simple' {
  declare module.exports: any;
}

declare module 'uglify-js/test/input/invalid/tab' {
  declare module.exports: any;
}

declare module 'uglify-js/test/input/issue-1236/simple' {
  declare module.exports: any;
}

declare module 'uglify-js/test/input/issue-1242/qux' {
  declare module.exports: any;
}

declare module 'uglify-js/test/input/issue-1323/sample' {
  declare module.exports: any;
}

declare module 'uglify-js/test/input/issue-1431/sample' {
  declare module.exports: any;
}

declare module 'uglify-js/test/input/issue-1482/bracketize' {
  declare module.exports: any;
}

declare module 'uglify-js/test/input/issue-1482/default' {
  declare module.exports: any;
}

declare module 'uglify-js/test/input/issue-1482/input' {
  declare module.exports: any;
}

declare module 'uglify-js/test/input/issue-1632/^{foo}[bar](baz)+$' {
  declare module.exports: any;
}

declare module 'uglify-js/test/input/issue-520/input' {
  declare module.exports: any;
}

declare module 'uglify-js/test/input/issue-520/output' {
  declare module.exports: any;
}

declare module 'uglify-js/test/jetstream' {
  declare module.exports: any;
}

declare module 'uglify-js/test/mocha' {
  declare module.exports: any;
}

declare module 'uglify-js/test/mocha/accessorTokens-1492' {
  declare module.exports: any;
}

declare module 'uglify-js/test/mocha/arguments' {
  declare module.exports: any;
}

declare module 'uglify-js/test/mocha/arrow' {
  declare module.exports: any;
}

declare module 'uglify-js/test/mocha/builtins' {
  declare module.exports: any;
}

declare module 'uglify-js/test/mocha/class' {
  declare module.exports: any;
}

declare module 'uglify-js/test/mocha/cli' {
  declare module.exports: any;
}

declare module 'uglify-js/test/mocha/comment_before_constant' {
  declare module.exports: any;
}

declare module 'uglify-js/test/mocha/comment-filter' {
  declare module.exports: any;
}

declare module 'uglify-js/test/mocha/comment' {
  declare module.exports: any;
}

declare module 'uglify-js/test/mocha/destructuring' {
  declare module.exports: any;
}

declare module 'uglify-js/test/mocha/directives' {
  declare module.exports: any;
}

declare module 'uglify-js/test/mocha/eof' {
  declare module.exports: any;
}

declare module 'uglify-js/test/mocha/export' {
  declare module.exports: any;
}

declare module 'uglify-js/test/mocha/expression' {
  declare module.exports: any;
}

declare module 'uglify-js/test/mocha/function' {
  declare module.exports: any;
}

declare module 'uglify-js/test/mocha/getter-setter' {
  declare module.exports: any;
}

declare module 'uglify-js/test/mocha/glob' {
  declare module.exports: any;
}

declare module 'uglify-js/test/mocha/huge-number-of-comments' {
  declare module.exports: any;
}

declare module 'uglify-js/test/mocha/input-sourcemaps' {
  declare module.exports: any;
}

declare module 'uglify-js/test/mocha/let' {
  declare module.exports: any;
}

declare module 'uglify-js/test/mocha/lhs-expressions' {
  declare module.exports: any;
}

declare module 'uglify-js/test/mocha/line-endings' {
  declare module.exports: any;
}

declare module 'uglify-js/test/mocha/minify-file-map' {
  declare module.exports: any;
}

declare module 'uglify-js/test/mocha/minify' {
  declare module.exports: any;
}

declare module 'uglify-js/test/mocha/new' {
  declare module.exports: any;
}

declare module 'uglify-js/test/mocha/number-literal' {
  declare module.exports: any;
}

declare module 'uglify-js/test/mocha/object' {
  declare module.exports: any;
}

declare module 'uglify-js/test/mocha/operator' {
  declare module.exports: any;
}

declare module 'uglify-js/test/mocha/release' {
  declare module.exports: any;
}

declare module 'uglify-js/test/mocha/screw-ie8' {
  declare module.exports: any;
}

declare module 'uglify-js/test/mocha/spidermonkey' {
  declare module.exports: any;
}

declare module 'uglify-js/test/mocha/string-literal' {
  declare module.exports: any;
}

declare module 'uglify-js/test/mocha/template-string' {
  declare module.exports: any;
}

declare module 'uglify-js/test/mocha/try' {
  declare module.exports: any;
}

declare module 'uglify-js/test/mocha/unicode' {
  declare module.exports: any;
}

declare module 'uglify-js/test/mocha/with' {
  declare module.exports: any;
}

declare module 'uglify-js/test/mocha/yield' {
  declare module.exports: any;
}

declare module 'uglify-js/test/mozilla-ast' {
  declare module.exports: any;
}

declare module 'uglify-js/test/run-tests' {
  declare module.exports: any;
}

declare module 'uglify-js/test/sandbox' {
  declare module.exports: any;
}

declare module 'uglify-js/test/sourcemaps' {
  declare module.exports: any;
}

declare module 'uglify-js/test/ufuzz' {
  declare module.exports: any;
}

declare module 'uglify-js/tools/exports' {
  declare module.exports: any;
}

declare module 'uglify-js/tools/node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'uglify-js/bin/extract-props.js' {
  declare module.exports: $Exports<'uglify-js/bin/extract-props'>;
}
declare module 'uglify-js/lib/ast.js' {
  declare module.exports: $Exports<'uglify-js/lib/ast'>;
}
declare module 'uglify-js/lib/compress.js' {
  declare module.exports: $Exports<'uglify-js/lib/compress'>;
}
declare module 'uglify-js/lib/mozilla-ast.js' {
  declare module.exports: $Exports<'uglify-js/lib/mozilla-ast'>;
}
declare module 'uglify-js/lib/output.js' {
  declare module.exports: $Exports<'uglify-js/lib/output'>;
}
declare module 'uglify-js/lib/parse.js' {
  declare module.exports: $Exports<'uglify-js/lib/parse'>;
}
declare module 'uglify-js/lib/propmangle.js' {
  declare module.exports: $Exports<'uglify-js/lib/propmangle'>;
}
declare module 'uglify-js/lib/scope.js' {
  declare module.exports: $Exports<'uglify-js/lib/scope'>;
}
declare module 'uglify-js/lib/sourcemap.js' {
  declare module.exports: $Exports<'uglify-js/lib/sourcemap'>;
}
declare module 'uglify-js/lib/transform.js' {
  declare module.exports: $Exports<'uglify-js/lib/transform'>;
}
declare module 'uglify-js/lib/utils.js' {
  declare module.exports: $Exports<'uglify-js/lib/utils'>;
}
declare module 'uglify-js/test/benchmark.js' {
  declare module.exports: $Exports<'uglify-js/test/benchmark'>;
}
declare module 'uglify-js/test/compress/angular-inject.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/angular-inject'>;
}
declare module 'uglify-js/test/compress/arrays.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/arrays'>;
}
declare module 'uglify-js/test/compress/arrow.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/arrow'>;
}
declare module 'uglify-js/test/compress/ascii.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/ascii'>;
}
declare module 'uglify-js/test/compress/asm.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/asm'>;
}
declare module 'uglify-js/test/compress/assignment.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/assignment'>;
}
declare module 'uglify-js/test/compress/block-scope.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/block-scope'>;
}
declare module 'uglify-js/test/compress/blocks.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/blocks'>;
}
declare module 'uglify-js/test/compress/collapse_vars.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/collapse_vars'>;
}
declare module 'uglify-js/test/compress/comparing.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/comparing'>;
}
declare module 'uglify-js/test/compress/concat-strings.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/concat-strings'>;
}
declare module 'uglify-js/test/compress/conditionals.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/conditionals'>;
}
declare module 'uglify-js/test/compress/const.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/const'>;
}
declare module 'uglify-js/test/compress/dead-code.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/dead-code'>;
}
declare module 'uglify-js/test/compress/debugger.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/debugger'>;
}
declare module 'uglify-js/test/compress/destructuring.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/destructuring'>;
}
declare module 'uglify-js/test/compress/directives.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/directives'>;
}
declare module 'uglify-js/test/compress/drop-console.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/drop-console'>;
}
declare module 'uglify-js/test/compress/drop-unused.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/drop-unused'>;
}
declare module 'uglify-js/test/compress/evaluate.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/evaluate'>;
}
declare module 'uglify-js/test/compress/expansions.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/expansions'>;
}
declare module 'uglify-js/test/compress/expression.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/expression'>;
}
declare module 'uglify-js/test/compress/functions.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/functions'>;
}
declare module 'uglify-js/test/compress/global_defs.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/global_defs'>;
}
declare module 'uglify-js/test/compress/harmony.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/harmony'>;
}
declare module 'uglify-js/test/compress/hoist_vars.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/hoist_vars'>;
}
declare module 'uglify-js/test/compress/hoist.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/hoist'>;
}
declare module 'uglify-js/test/compress/html_comments.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/html_comments'>;
}
declare module 'uglify-js/test/compress/if_return.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/if_return'>;
}
declare module 'uglify-js/test/compress/issue-1001.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-1001'>;
}
declare module 'uglify-js/test/compress/issue-1034.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-1034'>;
}
declare module 'uglify-js/test/compress/issue-1041.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-1041'>;
}
declare module 'uglify-js/test/compress/issue-1043.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-1043'>;
}
declare module 'uglify-js/test/compress/issue-1044.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-1044'>;
}
declare module 'uglify-js/test/compress/issue-1052.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-1052'>;
}
declare module 'uglify-js/test/compress/issue-1105.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-1105'>;
}
declare module 'uglify-js/test/compress/issue-12.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-12'>;
}
declare module 'uglify-js/test/compress/issue-1202.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-1202'>;
}
declare module 'uglify-js/test/compress/issue-1212.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-1212'>;
}
declare module 'uglify-js/test/compress/issue-126.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-126'>;
}
declare module 'uglify-js/test/compress/issue-1261.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-1261'>;
}
declare module 'uglify-js/test/compress/issue-1275.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-1275'>;
}
declare module 'uglify-js/test/compress/issue-1321.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-1321'>;
}
declare module 'uglify-js/test/compress/issue-143.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-143'>;
}
declare module 'uglify-js/test/compress/issue-1431.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-1431'>;
}
declare module 'uglify-js/test/compress/issue-1443.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-1443'>;
}
declare module 'uglify-js/test/compress/issue-1446.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-1446'>;
}
declare module 'uglify-js/test/compress/issue-1447.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-1447'>;
}
declare module 'uglify-js/test/compress/issue-1466.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-1466'>;
}
declare module 'uglify-js/test/compress/issue-1569.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-1569'>;
}
declare module 'uglify-js/test/compress/issue-1588.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-1588'>;
}
declare module 'uglify-js/test/compress/issue-1609.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-1609'>;
}
declare module 'uglify-js/test/compress/issue-1639.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-1639'>;
}
declare module 'uglify-js/test/compress/issue-1656.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-1656'>;
}
declare module 'uglify-js/test/compress/issue-1673.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-1673'>;
}
declare module 'uglify-js/test/compress/issue-1704.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-1704'>;
}
declare module 'uglify-js/test/compress/issue-1733.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-1733'>;
}
declare module 'uglify-js/test/compress/issue-1750.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-1750'>;
}
declare module 'uglify-js/test/compress/issue-1770.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-1770'>;
}
declare module 'uglify-js/test/compress/issue-1787.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-1787'>;
}
declare module 'uglify-js/test/compress/issue-203.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-203'>;
}
declare module 'uglify-js/test/compress/issue-208.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-208'>;
}
declare module 'uglify-js/test/compress/issue-22.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-22'>;
}
declare module 'uglify-js/test/compress/issue-267.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-267'>;
}
declare module 'uglify-js/test/compress/issue-269.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-269'>;
}
declare module 'uglify-js/test/compress/issue-368.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-368'>;
}
declare module 'uglify-js/test/compress/issue-44.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-44'>;
}
declare module 'uglify-js/test/compress/issue-59.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-59'>;
}
declare module 'uglify-js/test/compress/issue-597.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-597'>;
}
declare module 'uglify-js/test/compress/issue-611.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-611'>;
}
declare module 'uglify-js/test/compress/issue-637.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-637'>;
}
declare module 'uglify-js/test/compress/issue-640.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-640'>;
}
declare module 'uglify-js/test/compress/issue-747.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-747'>;
}
declare module 'uglify-js/test/compress/issue-751.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-751'>;
}
declare module 'uglify-js/test/compress/issue-782.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-782'>;
}
declare module 'uglify-js/test/compress/issue-892.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-892'>;
}
declare module 'uglify-js/test/compress/issue-913.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-913'>;
}
declare module 'uglify-js/test/compress/issue-926.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-926'>;
}
declare module 'uglify-js/test/compress/issue-973.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-973'>;
}
declare module 'uglify-js/test/compress/issue-976.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-976'>;
}
declare module 'uglify-js/test/compress/issue-979.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/issue-979'>;
}
declare module 'uglify-js/test/compress/join-vars.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/join-vars'>;
}
declare module 'uglify-js/test/compress/labels.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/labels'>;
}
declare module 'uglify-js/test/compress/loops.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/loops'>;
}
declare module 'uglify-js/test/compress/max_line_len.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/max_line_len'>;
}
declare module 'uglify-js/test/compress/negate-iife.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/negate-iife'>;
}
declare module 'uglify-js/test/compress/new.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/new'>;
}
declare module 'uglify-js/test/compress/numbers.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/numbers'>;
}
declare module 'uglify-js/test/compress/object.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/object'>;
}
declare module 'uglify-js/test/compress/parameters.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/parameters'>;
}
declare module 'uglify-js/test/compress/properties.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/properties'>;
}
declare module 'uglify-js/test/compress/pure_funcs.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/pure_funcs'>;
}
declare module 'uglify-js/test/compress/pure_getters.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/pure_getters'>;
}
declare module 'uglify-js/test/compress/reduce_vars.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/reduce_vars'>;
}
declare module 'uglify-js/test/compress/return_undefined.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/return_undefined'>;
}
declare module 'uglify-js/test/compress/screw-ie8.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/screw-ie8'>;
}
declare module 'uglify-js/test/compress/sequences.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/sequences'>;
}
declare module 'uglify-js/test/compress/string-literal.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/string-literal'>;
}
declare module 'uglify-js/test/compress/super.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/super'>;
}
declare module 'uglify-js/test/compress/switch.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/switch'>;
}
declare module 'uglify-js/test/compress/template-string.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/template-string'>;
}
declare module 'uglify-js/test/compress/transform.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/transform'>;
}
declare module 'uglify-js/test/compress/try-catch.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/try-catch'>;
}
declare module 'uglify-js/test/compress/typeof.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/typeof'>;
}
declare module 'uglify-js/test/compress/unicode.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/unicode'>;
}
declare module 'uglify-js/test/compress/wrap_iife.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/wrap_iife'>;
}
declare module 'uglify-js/test/compress/yield.js' {
  declare module.exports: $Exports<'uglify-js/test/compress/yield'>;
}
declare module 'uglify-js/test/input/comments/filter.js' {
  declare module.exports: $Exports<'uglify-js/test/input/comments/filter'>;
}
declare module 'uglify-js/test/input/global_defs/nested.js' {
  declare module.exports: $Exports<'uglify-js/test/input/global_defs/nested'>;
}
declare module 'uglify-js/test/input/global_defs/simple.js' {
  declare module.exports: $Exports<'uglify-js/test/input/global_defs/simple'>;
}
declare module 'uglify-js/test/input/invalid/assign_1.js' {
  declare module.exports: $Exports<'uglify-js/test/input/invalid/assign_1'>;
}
declare module 'uglify-js/test/input/invalid/assign_2.js' {
  declare module.exports: $Exports<'uglify-js/test/input/invalid/assign_2'>;
}
declare module 'uglify-js/test/input/invalid/assign_3.js' {
  declare module.exports: $Exports<'uglify-js/test/input/invalid/assign_3'>;
}
declare module 'uglify-js/test/input/invalid/eof.js' {
  declare module.exports: $Exports<'uglify-js/test/input/invalid/eof'>;
}
declare module 'uglify-js/test/input/invalid/loop-no-body.js' {
  declare module.exports: $Exports<'uglify-js/test/input/invalid/loop-no-body'>;
}
declare module 'uglify-js/test/input/invalid/simple.js' {
  declare module.exports: $Exports<'uglify-js/test/input/invalid/simple'>;
}
declare module 'uglify-js/test/input/invalid/tab.js' {
  declare module.exports: $Exports<'uglify-js/test/input/invalid/tab'>;
}
declare module 'uglify-js/test/input/issue-1236/simple.js' {
  declare module.exports: $Exports<'uglify-js/test/input/issue-1236/simple'>;
}
declare module 'uglify-js/test/input/issue-1242/qux.js' {
  declare module.exports: $Exports<'uglify-js/test/input/issue-1242/qux'>;
}
declare module 'uglify-js/test/input/issue-1323/sample.js' {
  declare module.exports: $Exports<'uglify-js/test/input/issue-1323/sample'>;
}
declare module 'uglify-js/test/input/issue-1431/sample.js' {
  declare module.exports: $Exports<'uglify-js/test/input/issue-1431/sample'>;
}
declare module 'uglify-js/test/input/issue-1482/bracketize.js' {
  declare module.exports: $Exports<'uglify-js/test/input/issue-1482/bracketize'>;
}
declare module 'uglify-js/test/input/issue-1482/default.js' {
  declare module.exports: $Exports<'uglify-js/test/input/issue-1482/default'>;
}
declare module 'uglify-js/test/input/issue-1482/input.js' {
  declare module.exports: $Exports<'uglify-js/test/input/issue-1482/input'>;
}
declare module 'uglify-js/test/input/issue-1632/^{foo}[bar](baz)+$.js' {
  declare module.exports: $Exports<'uglify-js/test/input/issue-1632/^{foo}[bar](baz)+$'>;
}
declare module 'uglify-js/test/input/issue-520/input.js' {
  declare module.exports: $Exports<'uglify-js/test/input/issue-520/input'>;
}
declare module 'uglify-js/test/input/issue-520/output.js' {
  declare module.exports: $Exports<'uglify-js/test/input/issue-520/output'>;
}
declare module 'uglify-js/test/jetstream.js' {
  declare module.exports: $Exports<'uglify-js/test/jetstream'>;
}
declare module 'uglify-js/test/mocha.js' {
  declare module.exports: $Exports<'uglify-js/test/mocha'>;
}
declare module 'uglify-js/test/mocha/accessorTokens-1492.js' {
  declare module.exports: $Exports<'uglify-js/test/mocha/accessorTokens-1492'>;
}
declare module 'uglify-js/test/mocha/arguments.js' {
  declare module.exports: $Exports<'uglify-js/test/mocha/arguments'>;
}
declare module 'uglify-js/test/mocha/arrow.js' {
  declare module.exports: $Exports<'uglify-js/test/mocha/arrow'>;
}
declare module 'uglify-js/test/mocha/builtins.js' {
  declare module.exports: $Exports<'uglify-js/test/mocha/builtins'>;
}
declare module 'uglify-js/test/mocha/class.js' {
  declare module.exports: $Exports<'uglify-js/test/mocha/class'>;
}
declare module 'uglify-js/test/mocha/cli.js' {
  declare module.exports: $Exports<'uglify-js/test/mocha/cli'>;
}
declare module 'uglify-js/test/mocha/comment_before_constant.js' {
  declare module.exports: $Exports<'uglify-js/test/mocha/comment_before_constant'>;
}
declare module 'uglify-js/test/mocha/comment-filter.js' {
  declare module.exports: $Exports<'uglify-js/test/mocha/comment-filter'>;
}
declare module 'uglify-js/test/mocha/comment.js' {
  declare module.exports: $Exports<'uglify-js/test/mocha/comment'>;
}
declare module 'uglify-js/test/mocha/destructuring.js' {
  declare module.exports: $Exports<'uglify-js/test/mocha/destructuring'>;
}
declare module 'uglify-js/test/mocha/directives.js' {
  declare module.exports: $Exports<'uglify-js/test/mocha/directives'>;
}
declare module 'uglify-js/test/mocha/eof.js' {
  declare module.exports: $Exports<'uglify-js/test/mocha/eof'>;
}
declare module 'uglify-js/test/mocha/export.js' {
  declare module.exports: $Exports<'uglify-js/test/mocha/export'>;
}
declare module 'uglify-js/test/mocha/expression.js' {
  declare module.exports: $Exports<'uglify-js/test/mocha/expression'>;
}
declare module 'uglify-js/test/mocha/function.js' {
  declare module.exports: $Exports<'uglify-js/test/mocha/function'>;
}
declare module 'uglify-js/test/mocha/getter-setter.js' {
  declare module.exports: $Exports<'uglify-js/test/mocha/getter-setter'>;
}
declare module 'uglify-js/test/mocha/glob.js' {
  declare module.exports: $Exports<'uglify-js/test/mocha/glob'>;
}
declare module 'uglify-js/test/mocha/huge-number-of-comments.js' {
  declare module.exports: $Exports<'uglify-js/test/mocha/huge-number-of-comments'>;
}
declare module 'uglify-js/test/mocha/input-sourcemaps.js' {
  declare module.exports: $Exports<'uglify-js/test/mocha/input-sourcemaps'>;
}
declare module 'uglify-js/test/mocha/let.js' {
  declare module.exports: $Exports<'uglify-js/test/mocha/let'>;
}
declare module 'uglify-js/test/mocha/lhs-expressions.js' {
  declare module.exports: $Exports<'uglify-js/test/mocha/lhs-expressions'>;
}
declare module 'uglify-js/test/mocha/line-endings.js' {
  declare module.exports: $Exports<'uglify-js/test/mocha/line-endings'>;
}
declare module 'uglify-js/test/mocha/minify-file-map.js' {
  declare module.exports: $Exports<'uglify-js/test/mocha/minify-file-map'>;
}
declare module 'uglify-js/test/mocha/minify.js' {
  declare module.exports: $Exports<'uglify-js/test/mocha/minify'>;
}
declare module 'uglify-js/test/mocha/new.js' {
  declare module.exports: $Exports<'uglify-js/test/mocha/new'>;
}
declare module 'uglify-js/test/mocha/number-literal.js' {
  declare module.exports: $Exports<'uglify-js/test/mocha/number-literal'>;
}
declare module 'uglify-js/test/mocha/object.js' {
  declare module.exports: $Exports<'uglify-js/test/mocha/object'>;
}
declare module 'uglify-js/test/mocha/operator.js' {
  declare module.exports: $Exports<'uglify-js/test/mocha/operator'>;
}
declare module 'uglify-js/test/mocha/release.js' {
  declare module.exports: $Exports<'uglify-js/test/mocha/release'>;
}
declare module 'uglify-js/test/mocha/screw-ie8.js' {
  declare module.exports: $Exports<'uglify-js/test/mocha/screw-ie8'>;
}
declare module 'uglify-js/test/mocha/spidermonkey.js' {
  declare module.exports: $Exports<'uglify-js/test/mocha/spidermonkey'>;
}
declare module 'uglify-js/test/mocha/string-literal.js' {
  declare module.exports: $Exports<'uglify-js/test/mocha/string-literal'>;
}
declare module 'uglify-js/test/mocha/template-string.js' {
  declare module.exports: $Exports<'uglify-js/test/mocha/template-string'>;
}
declare module 'uglify-js/test/mocha/try.js' {
  declare module.exports: $Exports<'uglify-js/test/mocha/try'>;
}
declare module 'uglify-js/test/mocha/unicode.js' {
  declare module.exports: $Exports<'uglify-js/test/mocha/unicode'>;
}
declare module 'uglify-js/test/mocha/with.js' {
  declare module.exports: $Exports<'uglify-js/test/mocha/with'>;
}
declare module 'uglify-js/test/mocha/yield.js' {
  declare module.exports: $Exports<'uglify-js/test/mocha/yield'>;
}
declare module 'uglify-js/test/mozilla-ast.js' {
  declare module.exports: $Exports<'uglify-js/test/mozilla-ast'>;
}
declare module 'uglify-js/test/run-tests.js' {
  declare module.exports: $Exports<'uglify-js/test/run-tests'>;
}
declare module 'uglify-js/test/sandbox.js' {
  declare module.exports: $Exports<'uglify-js/test/sandbox'>;
}
declare module 'uglify-js/test/sourcemaps.js' {
  declare module.exports: $Exports<'uglify-js/test/sourcemaps'>;
}
declare module 'uglify-js/test/ufuzz.js' {
  declare module.exports: $Exports<'uglify-js/test/ufuzz'>;
}
declare module 'uglify-js/tools/exports.js' {
  declare module.exports: $Exports<'uglify-js/tools/exports'>;
}
declare module 'uglify-js/tools/node.js' {
  declare module.exports: $Exports<'uglify-js/tools/node'>;
}
