// flow-typed signature: d25f55ec929cfbb04c7d24a3419399f2
// flow-typed version: <<STUB>>/uglifyjs-webpack-plugin_v0.4.3/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uglifyjs-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uglifyjs-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'uglifyjs-webpack-plugin/dist/index' {
  declare module.exports: any;
}

declare module 'uglifyjs-webpack-plugin/lib/post_install' {
  declare module.exports: any;
}

// Filename aliases
declare module 'uglifyjs-webpack-plugin/dist/index.js' {
  declare module.exports: $Exports<'uglifyjs-webpack-plugin/dist/index'>;
}
declare module 'uglifyjs-webpack-plugin/lib/post_install.js' {
  declare module.exports: $Exports<'uglifyjs-webpack-plugin/lib/post_install'>;
}
