// flow-typed signature: 80a36fd5ececff7ab7d8c9d49c1afae5
// flow-typed version: <<STUB>>/uglify-es_v3.3.9/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uglify-es'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uglify-es' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'uglify-es/lib/ast' {
  declare module.exports: any;
}

declare module 'uglify-es/lib/compress' {
  declare module.exports: any;
}

declare module 'uglify-es/lib/minify' {
  declare module.exports: any;
}

declare module 'uglify-es/lib/mozilla-ast' {
  declare module.exports: any;
}

declare module 'uglify-es/lib/output' {
  declare module.exports: any;
}

declare module 'uglify-es/lib/parse' {
  declare module.exports: any;
}

declare module 'uglify-es/lib/propmangle' {
  declare module.exports: any;
}

declare module 'uglify-es/lib/scope' {
  declare module.exports: any;
}

declare module 'uglify-es/lib/sourcemap' {
  declare module.exports: any;
}

declare module 'uglify-es/lib/transform' {
  declare module.exports: any;
}

declare module 'uglify-es/lib/utils' {
  declare module.exports: any;
}

declare module 'uglify-es/tools/exit' {
  declare module.exports: any;
}

declare module 'uglify-es/tools/exports' {
  declare module.exports: any;
}

declare module 'uglify-es/tools/node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'uglify-es/lib/ast.js' {
  declare module.exports: $Exports<'uglify-es/lib/ast'>;
}
declare module 'uglify-es/lib/compress.js' {
  declare module.exports: $Exports<'uglify-es/lib/compress'>;
}
declare module 'uglify-es/lib/minify.js' {
  declare module.exports: $Exports<'uglify-es/lib/minify'>;
}
declare module 'uglify-es/lib/mozilla-ast.js' {
  declare module.exports: $Exports<'uglify-es/lib/mozilla-ast'>;
}
declare module 'uglify-es/lib/output.js' {
  declare module.exports: $Exports<'uglify-es/lib/output'>;
}
declare module 'uglify-es/lib/parse.js' {
  declare module.exports: $Exports<'uglify-es/lib/parse'>;
}
declare module 'uglify-es/lib/propmangle.js' {
  declare module.exports: $Exports<'uglify-es/lib/propmangle'>;
}
declare module 'uglify-es/lib/scope.js' {
  declare module.exports: $Exports<'uglify-es/lib/scope'>;
}
declare module 'uglify-es/lib/sourcemap.js' {
  declare module.exports: $Exports<'uglify-es/lib/sourcemap'>;
}
declare module 'uglify-es/lib/transform.js' {
  declare module.exports: $Exports<'uglify-es/lib/transform'>;
}
declare module 'uglify-es/lib/utils.js' {
  declare module.exports: $Exports<'uglify-es/lib/utils'>;
}
declare module 'uglify-es/tools/exit.js' {
  declare module.exports: $Exports<'uglify-es/tools/exit'>;
}
declare module 'uglify-es/tools/exports.js' {
  declare module.exports: $Exports<'uglify-es/tools/exports'>;
}
declare module 'uglify-es/tools/node.js' {
  declare module.exports: $Exports<'uglify-es/tools/node'>;
}
