// flow-typed signature: 6d724caed5380e2f51bf775d26d930a7
// flow-typed version: <<STUB>>/webpack-parallel-uglify-plugin_v1.1.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-parallel-uglify-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-parallel-uglify-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-parallel-uglify-plugin/lib/cache' {
  declare module.exports: any;
}

declare module 'webpack-parallel-uglify-plugin/lib/tmp-file' {
  declare module.exports: any;
}

declare module 'webpack-parallel-uglify-plugin/lib/uglifier' {
  declare module.exports: any;
}

declare module 'webpack-parallel-uglify-plugin/lib/worker' {
  declare module.exports: any;
}

declare module 'webpack-parallel-uglify-plugin/test/index' {
  declare module.exports: any;
}

declare module 'webpack-parallel-uglify-plugin/test/lib/cache' {
  declare module.exports: any;
}

declare module 'webpack-parallel-uglify-plugin/test/lib/tmp-file' {
  declare module.exports: any;
}

declare module 'webpack-parallel-uglify-plugin/test/lib/uglifer' {
  declare module.exports: any;
}

declare module 'webpack-parallel-uglify-plugin/test/lib/worker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-parallel-uglify-plugin/index' {
  declare module.exports: $Exports<'webpack-parallel-uglify-plugin'>;
}
declare module 'webpack-parallel-uglify-plugin/index.js' {
  declare module.exports: $Exports<'webpack-parallel-uglify-plugin'>;
}
declare module 'webpack-parallel-uglify-plugin/lib/cache.js' {
  declare module.exports: $Exports<'webpack-parallel-uglify-plugin/lib/cache'>;
}
declare module 'webpack-parallel-uglify-plugin/lib/tmp-file.js' {
  declare module.exports: $Exports<'webpack-parallel-uglify-plugin/lib/tmp-file'>;
}
declare module 'webpack-parallel-uglify-plugin/lib/uglifier.js' {
  declare module.exports: $Exports<'webpack-parallel-uglify-plugin/lib/uglifier'>;
}
declare module 'webpack-parallel-uglify-plugin/lib/worker.js' {
  declare module.exports: $Exports<'webpack-parallel-uglify-plugin/lib/worker'>;
}
declare module 'webpack-parallel-uglify-plugin/test/index.js' {
  declare module.exports: $Exports<'webpack-parallel-uglify-plugin/test/index'>;
}
declare module 'webpack-parallel-uglify-plugin/test/lib/cache.js' {
  declare module.exports: $Exports<'webpack-parallel-uglify-plugin/test/lib/cache'>;
}
declare module 'webpack-parallel-uglify-plugin/test/lib/tmp-file.js' {
  declare module.exports: $Exports<'webpack-parallel-uglify-plugin/test/lib/tmp-file'>;
}
declare module 'webpack-parallel-uglify-plugin/test/lib/uglifer.js' {
  declare module.exports: $Exports<'webpack-parallel-uglify-plugin/test/lib/uglifer'>;
}
declare module 'webpack-parallel-uglify-plugin/test/lib/worker.js' {
  declare module.exports: $Exports<'webpack-parallel-uglify-plugin/test/lib/worker'>;
}
