import React from 'react';
import PropTypes from 'prop-types';

/**
 * `Field` component.
 *
 * Used to connect any form field to the form state generated by the
 * `createForm` HOC.
 *
 * The prop `component` can be a Component, a stateless function component, or
 * a string for DOM form fields (`input`, `select`). This is the component that will
 * be rendered.
 */
class Field extends React.Component {
  static propTypes = {
    component: PropTypes.oneOfType([PropTypes.func, PropTypes.string]),
    onBlur: PropTypes.func.isRequired,
    onChange: PropTypes.func.isRequired,
    name: PropTypes.string.isRequired,
    blurred: PropTypes.bool,
    error: PropTypes.string,
    value: PropTypes.any,
    initialValue: PropTypes.any,
    handleRef: PropTypes.func,
  };

  static defaultProps = {
    component: 'input',
    blurred: false,
    error: '',
    initialValue: null,
    value: null,
    handleRef: null,
  };

  /**
   * Return a field value from a SyntheticEvent or a value
   */
  getValue = eventOrValue => {
    const target = eventOrValue.target;
    if (target) {
      const type = target.type;
      if (type === 'checkbox') {
        return target.checked || '';
      }
      return target.value;
    }
    return eventOrValue;
  };

  /**
   * Handle change from the underlying component
   */
  handleChange = eventOrValue => {
    const value = this.getValue(eventOrValue);
    this.props.onChange(value);
  };

  render() {
    const {
      component,
      name,
      onBlur,
      onChange,
      blurred,
      error,
      value,
      initialValue,
      handleRef,
      ...otherProps
    } = this.props;

    // form-related props
    const customProps = {
      name,
      value,
      onBlur,
      onChange: this.handleChange,
      ref: handleRef,
    };

    // form-related props that might cause an "unknown prop" warnings
    const extraProps = {
      blurred,
      error,
      initialValue,
    };

    if (typeof component === 'string') {
      // don't pass extra props if component is a string, because
      // it can trigger "unknown prop" warnings
      return React.createElement(component, { ...customProps, ...otherProps });
    }
    return React.createElement(component, { ...customProps, ...extraProps, ...otherProps });
  }
}

export default Field;
