Feature: Test budgeting app

  Scenario: You able to add new record to app
    Given I am on "http://localhost:3000/"
    When I select category "Utensils" in "categoriesSelect"
    And I fill in "description" with "Ebay sale - guitar"
    And I fill in "value" with "100"
    And I click on "add"
    Then I should see "Utensils" in "addedCategory"
    Then I should see "Ebay sale - guitar" in "addedDescription"
    Then I should see "-$100.00" in "addedValue"
    Then I should see "$2,113.93" in "totalBalance"

  Scenario: All possible reports categories are groped and contain proper total value
    Given I am on "http://localhost:3000/"
    When I select category "Utensils" in "categoriesSelect"
    And I fill in "value" with "100"
    And I click on "addBtn"
    And I should see "Utensils" in "addedCategory"
    And I should see "-$100.00" in "addedValue"
    When I select category "School" in "categoriesSelect"
    And I fill in "value" with "100"
    And I click on "addBtn"
    And I should see "School" in "addedCategory"
    And I should see "-$100.00" in "addedValue"
    When I select category "Entertainment" in "categoriesSelect"
    And I fill in "value" with "100"
    And I click on "addBtn"
    And I should see "Entertainment" in "addedCategory"
    And I should see "-$100.00" in "addedValue"
    When I select category "Kids" in "categoriesSelect"
    And I fill in "value" with "100"
    And I click on "addBtn"
    And I should see "Kids" in "addedCategory"
    And I should see "-$100.00" in "addedValue"
    And I click on "reportsLink"
    Then Category "Kids" should be only "1" and balance is "$100.00"
    Then Category "School" should be only "1" and balance is "$100.00"
    Then Category "Utensils" should be only "1" and balance is "$100.00"
    Then Category "Groceries" should be only "1" and balance is "$423.34"
    Then Category "Travel" should be only "1" and balance is "$764.73"
    Then Category "Misc" should be only "1" and balance is "$1,100.00"
    Then Category "Entertainment" should be only "1" and balance is "$2,400.00"


  Scenario: All Categories, except income, should subtract value from your
    Given I am on "http://localhost:3000/"
    When I select category "Utensils" in "categoriesSelect"
    And I fill in "value" with "100"
    And I click on "addBtn"
    And I should see "Utensils" in "addedCategory"
    And I should see "-$100.00" in "addedValue"
    When I select category "School" in "categoriesSelect"
    And I fill in "value" with "100"
    And I click on "addBtn"
    And I should see "School" in "addedCategory"
    And I should see "-$100.00" in "addedValue"
    When I select category "Entertainment" in "categoriesSelect"
    And I fill in "value" with "100"
    And I click on "addBtn"
    And I should see "Entertainment" in "addedCategory"
    And I should see "-$100.00" in "addedValue"
    When I select category "Income" in "categoriesSelect"
    And I fill in "value" with "100"
    And I click on "addBtn"
    Then I should see "Income" in "addedCategory"
    Then I should see "$100.00" in "addedValue"

    ## This test should be failed ##
  Scenario: ‘Value’ could not be empty
    Given I am on "http://localhost:3000/"
    When I select category "Utensils" in "categoriesSelect"
    And I fill in "description" with "Ebay sale - guitar"
    And I click on "addBtn"
    Then I should see "Utensils" in "addedCategory"
    Then I should see "Ebay sale - guitar" in "addedDescription"
